# Generated by Django 5.2.13 on 2026-09-04 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0068_gendocumentodetalle_almacen'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvExistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('existencia', models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20)),
                ('remision', models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20)),
                ('disponible', models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='existencias_almacen_rel', to='inventario.invalmacen')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='existencias_item_rel', to='general.genitem')),
            ],
            options={
                'verbose_name': 'Existencia',
                'verbose_name_plural': 'Existencias',
                'db_table': 'inv_existencia',
                'ordering': ['-id'],
                'constraints': [models.UniqueConstraint(fields=('item', 'almacen'), name='inv_existencia_item_almacen_unico')],
            },
        ),
    ]
