from .adicional import HumAdicional
from .aporte import HumAporte
from .aporte_contrato import HumAporteContrato
from .aporte_detalle import HumAporteDetalle
from .aporte_entidad import HumAporteEntidad
from .cargo import HumCargo
from .concepto import HumConcepto
from .concepto_cuenta import HumConceptoCuenta
from .concepto_nomina import HumConceptoNomina
from .concepto_tipo import HumConceptoTipo
from .configuracion_aporte import HumConfiguracionAporte
from .configuracion_provision import HumConfiguracionProvision
from .contrato import HumContrato
from .contrato_tipo import HumContratoTipo
from .credito import HumCredito
from .entidad import HumEntidad
from .grupo import HumGrupo
from .liquidacion import HumLiquidacion
from .liquidacion_adicional import HumLiquidacionAdicional
from .motivo_terminacion import HumMotivoTerminacion
from .novedad import HumNovedad
from .novedad_tipo import HumNovedadTipo
from .pago_tipo import HumPagoTipo
from .pension import HumPension
from .periodo import HumPeriodo
from .programacion import HumProgramacion
from .programacion_detalle import HumProgramacionDetalle
from .riesgo import HumRiesgo
from .salud import HumSalud
from .subtipo_cotizante import HumSubtipoCotizante
from .sucursal import HumSucursal
from .tiempo import HumTiempo
from .tipo_costo import HumTipoCosto
from .tipo_cotizante import HumTipoCotizante
