from .programacion import TurProgramacionViewSet
from .programacion_simulacion import TurProgramacionSimulacionViewSet
from .programador import TurProgramadorViewSet
from .prototipo import TurPrototipoViewSet
from .puesto import TurPuestoViewSet
from .secuencia import TurSecuenciaViewSet
from .soporte import TurSoporteViewSet
from .soporte_detalle import TurSoporteDetalleViewSet
from .turno import TurTurnoViewSet
