# Generated by Django 6.0.4 on 2026-06-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HumConceptoTipo',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Concepto tipo',
                'verbose_name_plural': 'Conceptos tipos',
                'db_table': 'hum_concepto_tipo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HumContratoTipo',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Contrato tipo',
                'verbose_name_plural': 'Contratos tipos',
                'db_table': 'hum_contrato_tipo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HumMotivoTerminacion',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Motivo terminación',
                'verbose_name_plural': 'Motivos terminación',
                'db_table': 'hum_motivo_terminacion',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HumPagoTipo',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('aplica_programacion', models.BooleanField(db_default=False, default=False)),
            ],
            options={
                'verbose_name': 'Pago tipo',
                'verbose_name_plural': 'Pagos tipos',
                'db_table': 'hum_pago_tipo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HumPeriodo',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=200)),
                ('dias', models.IntegerField(db_default=0, default=0)),
            ],
            options={
                'verbose_name': 'Periodo',
                'verbose_name_plural': 'Periodos',
                'db_table': 'hum_periodo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HumRiesgo',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('porcentaje', models.DecimalField(db_default=0, decimal_places=3, default=0, max_digits=6)),
            ],
            options={
                'verbose_name': 'Riesgo',
                'verbose_name_plural': 'Riesgos',
                'db_table': 'hum_riesgo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HumSubtipoCotizante',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Subtipo cotizante',
                'verbose_name_plural': 'Subtipos cotizantes',
                'db_table': 'hum_subtipo_cotizante',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HumTiempo',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Tiempo',
                'verbose_name_plural': 'Tiempos',
                'db_table': 'hum_tiempo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HumTipoCosto',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Tipo costo',
                'verbose_name_plural': 'Tipos costos',
                'db_table': 'hum_tipo_costo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HumTipoCotizante',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Tipo cotizante',
                'verbose_name_plural': 'Tipos cotizantes',
                'db_table': 'hum_tipo_cotizante',
                'ordering': ['nombre'],
            },
        ),
    ]
