# Generated by Django 6.0.4 on 2026-06-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumEntidad',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20)),
                ('numero_identificacion', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=200)),
                ('nombre_extendido', models.CharField(max_length=200, null=True)),
                ('salud', models.BooleanField(db_default=False, default=False)),
                ('pension', models.BooleanField(db_default=False, default=False)),
                ('cesantias', models.BooleanField(db_default=False, default=False)),
                ('caja', models.BooleanField(db_default=False, default=False)),
                ('riesgo', models.BooleanField(db_default=False, default=False)),
                ('sena', models.BooleanField(db_default=False, default=False)),
                ('icbf', models.BooleanField(db_default=False, default=False)),
            ],
            options={
                'verbose_name': 'Entidad',
                'verbose_name_plural': 'Entidades',
                'db_table': 'hum_entidad',
                'ordering': ['nombre'],
            },
        ),
    ]
