# Generated by Django 6.0.4 on 2026-06-04 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0002_humentidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=200)),
                ('estado_inactivo', models.BooleanField(db_default=False, default=False)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'db_table': 'hum_cargo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HumSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('codigo', models.CharField(max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'db_table': 'hum_sucursal',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HumConcepto',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('porcentaje', models.DecimalField(db_default=0, decimal_places=3, default=0, max_digits=6)),
                ('ingreso_base_prestacion', models.BooleanField(db_default=False, default=False)),
                ('ingreso_base_prestacion_vacacion', models.BooleanField(db_default=False, default=False)),
                ('ingreso_base_cotizacion', models.BooleanField(db_default=False, default=False)),
                ('operacion', models.BigIntegerField(db_default=0, default=0)),
                ('orden', models.IntegerField(db_default=0, default=0)),
                ('adicional', models.BooleanField(db_default=False, default=False)),
                ('concepto_tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conceptos_concepto_tipo_rel', to='humano.humconceptotipo')),
            ],
            options={
                'verbose_name': 'Concepto',
                'verbose_name_plural': 'Conceptos',
                'db_table': 'hum_concepto',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='HumGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('periodo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grupos_periodo_rel', to='humano.humperiodo')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'db_table': 'hum_grupo',
                'ordering': ['nombre'],
            },
        ),
    ]
