# Generated by Django 6.0.4 on 2026-06-04 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0003_humcargo_humsucursal_humconcepto_humgrupo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumConceptoNomina',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('concepto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conceptos_nomina_concepto_rel', to='humano.humconcepto')),
            ],
            options={
                'verbose_name': 'Concepto nómina',
                'verbose_name_plural': 'Conceptos nómina',
                'db_table': 'hum_concepto_nomina',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HumNovedadTipo',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('novedad_clase_id', models.IntegerField(null=True)),
                ('concepto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='novedades_tipos_concepto_rel', to='humano.humconcepto')),
                ('concepto2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='novedades_tipos_concepto2_rel', to='humano.humconcepto')),
            ],
            options={
                'verbose_name': 'Novedad tipo',
                'verbose_name_plural': 'Novedades tipos',
                'db_table': 'hum_novedad_tipo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HumPension',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('porcentaje_empleado', models.DecimalField(db_default=0, decimal_places=3, default=0, max_digits=6)),
                ('porcentaje_empleador', models.DecimalField(db_default=0, decimal_places=3, default=0, max_digits=6)),
                ('concepto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pensiones_concepto_rel', to='humano.humconcepto')),
            ],
            options={
                'verbose_name': 'Pensión',
                'verbose_name_plural': 'Pensiones',
                'db_table': 'hum_pension',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HumSalud',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('porcentaje_empleado', models.DecimalField(db_default=4, decimal_places=3, default=4, max_digits=6)),
                ('concepto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='saludes_concepto_rel', to='humano.humconcepto')),
            ],
            options={
                'verbose_name': 'Salud',
                'verbose_name_plural': 'Saludes',
                'db_table': 'hum_salud',
                'ordering': ['nombre'],
            },
        ),
    ]
