# Generated by Django 6.0.4 on 2026-06-04 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0006_alter_concentrocosto_codigo'),
        ('humano', '0004_humconceptonomina_humnovedadtipo_humpension_humsalud'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumConceptoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conceptos_cuentas_concepto_rel', to='humano.humconcepto')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conceptos_cuentas_cuenta_rel', to='contabilidad.concuenta')),
                ('tipo_costo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conceptos_cuentas_tipo_costo_rel', to='humano.humtipocosto')),
            ],
            options={
                'verbose_name': 'Concepto cuenta',
                'verbose_name_plural': 'Conceptos cuentas',
                'db_table': 'hum_concepto_cuenta',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='HumConfiguracionAporte',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20, null=True)),
                ('orden', models.IntegerField(db_default=0, default=0)),
                ('cuenta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuraciones_aportes_cuenta_rel', to='contabilidad.concuenta')),
            ],
            options={
                'verbose_name': 'Configuración aporte',
                'verbose_name_plural': 'Configuraciones aportes',
                'db_table': 'hum_configuracion_aporte',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='HumConfiguracionProvision',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20, null=True)),
                ('orden', models.IntegerField(db_default=0, default=0)),
                ('cuenta_credito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuraciones_provisiones_cuenta_credito_rel', to='contabilidad.concuenta')),
                ('cuenta_debito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuraciones_provisiones_cuenta_debito_rel', to='contabilidad.concuenta')),
                ('tipo_costo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuraciones_provisiones_tipo_costo_rel', to='humano.humtipocosto')),
            ],
            options={
                'verbose_name': 'Configuración provisión',
                'verbose_name_plural': 'Configuraciones provisiones',
                'db_table': 'hum_configuracion_provision',
                'ordering': ['orden'],
            },
        ),
    ]
