# Generated by Django 6.0.4 on 2026-06-04 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0006_alter_concentrocosto_codigo'),
        ('general', '0035_genitemimpuesto'),
        ('humano', '0005_humconceptocuenta_humconfiguracionaporte_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
                ('salario', models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20)),
                ('auxilio_transporte', models.BooleanField(db_default=False, default=False)),
                ('salario_integral', models.BooleanField(db_default=False, default=False)),
                ('estado_terminado', models.BooleanField(db_default=False, default=False)),
                ('comentario', models.CharField(max_length=300, null=True)),
                ('fecha_ultimo_pago', models.DateField(null=True)),
                ('fecha_ultimo_pago_prima', models.DateField(null=True)),
                ('fecha_ultimo_pago_cesantia', models.DateField(null=True)),
                ('fecha_ultimo_pago_vacacion', models.DateField(null=True)),
                ('cargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_cargo_rel', to='humano.humcargo')),
                ('ciudad_contrato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_ciudad_contrato_rel', to='general.genciudad')),
                ('ciudad_labora', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_ciudad_labora_rel', to='general.genciudad')),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_contacto_rel', to='general.gencontacto')),
                ('contrato_tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_contrato_tipo_rel', to='humano.humcontratotipo')),
                ('entidad_caja', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_entidad_caja_rel', to='humano.humentidad')),
                ('entidad_cesantias', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_entidad_cesantias_rel', to='humano.humentidad')),
                ('entidad_pension', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_entidad_pension_rel', to='humano.humentidad')),
                ('entidad_salud', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_entidad_salud_rel', to='humano.humentidad')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_grupo_rel', to='humano.humgrupo')),
                ('grupo_contabilidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_grupo_contabilidad_rel', to='contabilidad.concentrocosto')),
                ('motivo_terminacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_motivo_terminacion_rel', to='humano.hummotivoterminacion')),
                ('pension', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_pension_rel', to='humano.humpension')),
                ('riesgo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_riesgo_rel', to='humano.humriesgo')),
                ('salud', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_salud_rel', to='humano.humsalud')),
                ('subtipo_cotizante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_subtipo_cotizante_rel', to='humano.humsubtipocotizante')),
                ('sucursal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_sucursal_rel', to='humano.humsucursal')),
                ('tiempo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_tiempo_rel', to='humano.humtiempo')),
                ('tipo_costo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_tipo_costo_rel', to='humano.humtipocosto')),
                ('tipo_cotizante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_tipo_cotizante_rel', to='humano.humtipocotizante')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'db_table': 'hum_contrato',
                'ordering': ['-id'],
            },
        ),
    ]
