# Generated by Django 6.0.4 on 2026-06-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0008_humaporte_humaportecontrato_humaportedetalle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='humcontrato',
            name='habilitado_turno',
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
