# Generated by Django 5.2.13 on 2026-09-05 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0016_consaldocuenta'),
        ('humano', '0010_rename_grupo_contabilidad_humcontrato_centro_costo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humcontrato',
            name='centro_costo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_centro_costo_rel', to='contabilidad.concentrocosto'),
        ),
    ]
