from .accion import GenAccion
from .archivo import GenArchivo
from .archivo_tipo import GenArchivoTipo
from .asesor import GenAsesor
from .documento import GenDocumento
from .documento_clase import GenDocumentoClase
from .documento_detalle import GenDocumentoDetalle
from .documento_impuesto import GenDocumentoImpuesto
from .documento_tipo import GenDocumentoTipo
from .banco import GenBanco
from .ciudad import GenCiudad
from .configuracion import GenConfiguracion
from .contacto import GenContacto
from .cuenta_banco import GenCuentaBanco
from .cuenta_banco_clase import GenCuentaBancoClase
from .cuenta_banco_tipo import GenCuentaBancoTipo
from .estado import GenEstado
from .festivo import GenFestivo
from .identificacion import GenIdentificacion
from .impuesto import GenImpuesto
from .impuesto_tipo import GenImpuestoTipo
from .item import GenItem
from .item_impuesto import GenItemImpuesto
from .log import GenLog
from .modalidad import GenModalidad
from .modelo import GenModelo
from .pais import GenPais
from .plazo_pago import GenPlazoPago
from .resolucion import GenResolucion
from .responsabilidad import GenResponsabilidad
from .precio import GenPrecio
from .precio_detalle import GenPrecioDetalle
from .sector import GenSector
from .tipo_persona import GenTipoPersona
