from .adicional import HumAdicionalViewSet
from .aporte import HumAporteViewSet
from .aporte_contrato import HumAporteContratoViewSet
from .aporte_detalle import HumAporteDetalleViewSet
from .aporte_entidad import HumAporteEntidadViewSet
from .cargo import HumCargoViewSet
from .concepto import HumConceptoViewSet
from .concepto_cuenta import HumConceptoCuentaViewSet
from .concepto_nomina import HumConceptoNominaViewSet
from .concepto_tipo import HumConceptoTipoViewSet
from .configuracion_aporte import HumConfiguracionAporteViewSet
from .configuracion_provision import HumConfiguracionProvisionViewSet
from .contrato import HumContratoViewSet
from .contrato_tipo import HumContratoTipoViewSet
from .credito import HumCreditoViewSet
from .entidad import HumEntidadViewSet
from .grupo import HumGrupoViewSet
from .liquidacion import HumLiquidacionViewSet
from .liquidacion_adicional import HumLiquidacionAdicionalViewSet
from .motivo_terminacion import HumMotivoTerminacionViewSet
from .novedad import HumNovedadViewSet
from .novedad_tipo import HumNovedadTipoViewSet
from .pago_tipo import HumPagoTipoViewSet
from .pension import HumPensionViewSet
from .periodo import HumPeriodoViewSet
from .programacion import HumProgramacionViewSet
from .programacion_detalle import HumProgramacionDetalleViewSet
from .riesgo import HumRiesgoViewSet
from .salud import HumSaludViewSet
from .subtipo_cotizante import HumSubtipoCotizanteViewSet
from .sucursal import HumSucursalViewSet
from .tiempo import HumTiempoViewSet
from .tipo_costo import HumTipoCostoViewSet
from .tipo_cotizante import HumTipoCotizanteViewSet
