# Generated by Django 6.0.4 on 2026-05-11 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConCuentaClase',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Clase de cuenta',
                'verbose_name_plural': 'Clases de cuenta',
                'db_table': 'con_cuenta_clase',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ConCuentaCuenta',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Cuenta contable',
                'verbose_name_plural': 'Cuentas contables',
                'db_table': 'con_cuenta_cuenta',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ConCuentaGrupo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Grupo de cuenta',
                'verbose_name_plural': 'Grupos de cuenta',
                'db_table': 'con_cuenta_grupo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ConCuentaSubcuenta',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Subcuenta',
                'verbose_name_plural': 'Subcuentas',
                'db_table': 'con_cuenta_subcuenta',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ConCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='0', max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('exige_base', models.BooleanField(default=False)),
                ('exige_contacto', models.BooleanField(default=False)),
                ('exige_grupo', models.BooleanField(default=False)),
                ('permite_movimiento', models.BooleanField(default=False)),
                ('nivel', models.IntegerField(null=True)),
                ('cuenta_clase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.concuentaclase')),
                ('cuenta_cuenta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.concuentacuenta')),
                ('cuenta_grupo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.concuentagrupo')),
                ('cuenta_subcuenta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.concuentasubcuenta')),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
                'db_table': 'con_cuenta',
                'ordering': ['codigo'],
            },
        ),
    ]
