# Generated by Django 6.0.4 on 2026-05-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_agregar_comprobante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concomprobante',
            name='permite_asiento',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='concuenta',
            name='codigo',
            field=models.CharField(db_default='0', default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='concuenta',
            name='exige_base',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='concuenta',
            name='exige_contacto',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='concuenta',
            name='exige_grupo',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='concuenta',
            name='permite_movimiento',
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
