# Generated by Django 6.0.4 on 2026-06-02 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0003_alter_concomprobante_permite_asiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConCentroCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_default='0', default='0', max_length=20)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Centro de costo',
                'verbose_name_plural': 'Centros de costo',
                'db_table': 'con_centro_costo',
                'ordering': ['codigo'],
            },
        ),
    ]
