# Generated by Django 6.0.4 on 2026-06-02 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0004_concentrocosto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concentrocosto',
            name='codigo',
            field=models.CharField(max_length=20),
        ),
    ]
