# Generated by Django 6.0.4 on 2026-06-02 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0005_alter_concentrocosto_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concentrocosto',
            name='codigo',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
