# Generated by Django 6.0.4 on 2026-06-04 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0006_alter_concentrocosto_codigo'),
        ('general', '0035_genitemimpuesto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConActivoGrupo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Grupo de activo',
                'verbose_name_plural': 'Grupos de activo',
                'db_table': 'con_activo_grupo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConMetodoDepreciacion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Método de depreciación',
                'verbose_name_plural': 'Métodos de depreciación',
                'db_table': 'con_metodo_depreciacion',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.BigIntegerField()),
                ('mes', models.BigIntegerField()),
                ('estado_bloqueado', models.BooleanField(db_default=False, default=False)),
                ('estado_cerrado', models.BooleanField(db_default=False, default=False)),
                ('estado_inconsistencia', models.BooleanField(db_default=False, default=False)),
            ],
            options={
                'verbose_name': 'Periodo',
                'verbose_name_plural': 'Periodos',
                'db_table': 'con_periodo',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ConConciliacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
                ('cuenta_banco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conciliaciones_cuenta_banco_rel', to='general.gencuentabanco')),
            ],
            options={
                'verbose_name': 'Conciliación',
                'verbose_name_plural': 'Conciliaciones',
                'db_table': 'con_conciliacion',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ConConciliacionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('debito', models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20)),
                ('credito', models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20)),
                ('detalle', models.CharField(max_length=150, null=True)),
                ('estado_conciliado', models.BooleanField(db_default=False, default=False)),
                ('conciliacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conciliaciones_detalles_conciliacion_rel', to='contabilidad.conconciliacion')),
                ('contacto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conciliaciones_detalles_contacto_rel', to='general.gencontacto')),
                ('cuenta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conciliaciones_detalles_cuenta_rel', to='contabilidad.concuenta')),
                ('documento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conciliaciones_detalles_documento_rel', to='general.gendocumento')),
            ],
            options={
                'verbose_name': 'Conciliación detalle',
                'verbose_name_plural': 'Conciliaciones detalles',
                'db_table': 'con_conciliacion_detalle',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ConConciliacionSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('debito', models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20)),
                ('credito', models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20)),
                ('detalle', models.CharField(max_length=150, null=True)),
                ('estado_conciliado', models.BooleanField(db_default=False, default=False)),
                ('conciliacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conciliaciones_soportes_conciliacion_rel', to='contabilidad.conconciliacion')),
            ],
            options={
                'verbose_name': 'Conciliación soporte',
                'verbose_name_plural': 'Conciliaciones soportes',
                'db_table': 'con_conciliacion_soporte',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ConActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100, null=True)),
                ('serie', models.CharField(max_length=100, null=True)),
                ('modelo', models.CharField(max_length=100, null=True)),
                ('fecha_compra', models.DateField()),
                ('fecha_activacion', models.DateField()),
                ('fecha_baja', models.DateField(null=True)),
                ('duracion', models.IntegerField(null=True)),
                ('valor_compra', models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20)),
                ('depreciacion_inicial', models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20)),
                ('depreciacion_periodo', models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20)),
                ('depreciacion_acumulada', models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20)),
                ('depreciacion_saldo', models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20)),
                ('cuenta_depreciacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos_cuenta_depreciacion_rel', to='contabilidad.concuenta')),
                ('cuenta_gasto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos_cuenta_gasto_rel', to='contabilidad.concuenta')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos_grupo_rel', to='contabilidad.concentrocosto')),
                ('activo_grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos_activo_grupo_rel', to='contabilidad.conactivogrupo')),
                ('metodo_depreciacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos_metodo_depreciacion_rel', to='contabilidad.conmetododepreciacion')),
            ],
            options={
                'verbose_name': 'Activo',
                'verbose_name_plural': 'Activos',
                'db_table': 'con_activo',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ConMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(null=True)),
                ('fecha', models.DateField()),
                ('debito', models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20)),
                ('credito', models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20)),
                ('base', models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20)),
                ('naturaleza', models.CharField(max_length=1)),
                ('detalle', models.CharField(max_length=150, null=True)),
                ('cierre', models.BooleanField(db_default=False, default=False)),
                ('saldo_inicial', models.BooleanField(db_default=False, default=False)),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_comprobante_rel', to='contabilidad.concomprobante')),
                ('contacto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_contacto_rel', to='general.gencontacto')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_cuenta_rel', to='contabilidad.concuenta')),
                ('documento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_documento_rel', to='general.gendocumento')),
                ('grupo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_grupo_rel', to='contabilidad.concentrocosto')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_periodo_rel', to='contabilidad.conperiodo')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'db_table': 'con_movimiento',
                'ordering': ['-id'],
            },
        ),
    ]
