# Generated by Django 6.0.4 on 2026-06-06 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0007_conactivogrupo_conmetododepreciacion_conperiodo_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conperiodo',
            unique_together={('anio', 'mes')},
        ),
    ]
