# Generated by Django 6.0.4 on 2026-06-06 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0008_alter_conperiodo_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concentrocosto',
            name='codigo',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='concuenta',
            name='codigo',
            field=models.CharField(db_default='0', default='0', max_length=20, unique=True),
        ),
    ]
