# Generated by Django 6.0.4 on 2026-06-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0009_alter_concentrocosto_codigo_alter_concuenta_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concuenta',
            name='codigo',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
