# Generated by Django 6.0.4 on 2026-06-19 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0011_rename_grupo_centro_costo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conactivo',
            name='centro_costo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos_centro_costo_rel', to='contabilidad.concentrocosto'),
        ),
        migrations.AlterField(
            model_name='conmovimiento',
            name='centro_costo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_centro_costo_rel', to='contabilidad.concentrocosto'),
        ),
    ]
