# Generated by Django 6.0.4 on 2026-06-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0012_alter_conactivo_centro_costo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concentrocosto',
            name='estado_inactivo',
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
