# Generated by Django 5.2.13 on 2026-09-03 11:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0013_concentrocosto_estado_inactivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conperiodo',
            name='anio',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AlterField(
            model_name='conperiodo',
            name='id',
            field=models.BigIntegerField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='conperiodo',
            name='mes',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(13)]),
        ),
    ]
