# Generated by Django 5.2.13 on 2026-09-04 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0015_rename_exige_grupo_concuenta_exige_centro_costo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConSaldoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debito', models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20)),
                ('credito', models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saldos_cuenta_rel', to='contabilidad.concuenta')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saldos_periodo_rel', to='contabilidad.conperiodo')),
            ],
            options={
                'verbose_name': 'Saldo de cuenta',
                'verbose_name_plural': 'Saldos de cuenta',
                'db_table': 'con_saldo_cuenta',
                'ordering': ['-id'],
                'constraints': [models.UniqueConstraint(fields=('periodo', 'cuenta'), name='con_saldo_cuenta_periodo_cuenta_unico')],
            },
        ),
    ]
