# Generated by Django 6.0.4 on 2026-05-11 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenAsesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_corto', models.CharField(max_length=200)),
                ('celular', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=255)),
            ],
            options={
                'verbose_name': 'Asesor',
                'verbose_name_plural': 'Asesores',
                'db_table': 'gen_asesor',
                'ordering': ['nombre_corto'],
            },
        ),
        migrations.CreateModel(
            name='GenBanco',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'db_table': 'gen_banco',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='GenCuentaBancoClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Clase de cuenta bancaria',
                'verbose_name_plural': 'Clases de cuenta bancaria',
                'db_table': 'gen_cuenta_banco_clase',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='GenCuentaBancoTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de cuenta bancaria',
                'verbose_name_plural': 'Tipos de cuenta bancaria',
                'db_table': 'gen_cuenta_banco_tipo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='GenEstado',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'gen_estado',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='GenPais',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('codigo', models.CharField(max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'db_table': 'gen_pais',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='GenPlazoPago',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('dias', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Plazo de pago',
                'verbose_name_plural': 'Plazos de pago',
                'db_table': 'gen_plazo_pago',
                'ordering': ['dias'],
            },
        ),
        migrations.CreateModel(
            name='GenPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('venta', models.BooleanField(default=False)),
                ('compra', models.BooleanField(default=False)),
                ('fecha_vence', models.DateField()),
            ],
            options={
                'verbose_name': 'Precio',
                'verbose_name_plural': 'Precios',
                'db_table': 'gen_precio',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='GenTipoPersona',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Tipo de persona',
                'verbose_name_plural': 'Tipos de persona',
                'db_table': 'gen_tipo_persona',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='GenCuentaBanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numero_cuenta', models.CharField(max_length=50, null=True)),
                ('cuenta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_bancos_cuenta_rel', to='contabilidad.concuenta')),
                ('cuenta_banco_clase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_bancos_cuenta_banco_clase', to='general.gencuentabancoclase')),
                ('cuenta_banco_tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_bancos_cuenta_banco_tipo', to='general.gencuentabancotipo')),
            ],
            options={
                'verbose_name': 'Cuenta bancaria',
                'verbose_name_plural': 'Cuentas bancarias',
                'db_table': 'gen_cuenta_banco',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='GenCiudad',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('latitud', models.CharField(max_length=20, null=True)),
                ('longitud', models.CharField(max_length=20, null=True)),
                ('codigo_postal', models.CharField(max_length=10, null=True)),
                ('porcentaje_impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('codigo', models.CharField(max_length=10, null=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.genestado')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'db_table': 'gen_ciudad',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='GenIdentificacion',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('abreviatura', models.CharField(max_length=10, null=True)),
                ('orden', models.BigIntegerField(default=0)),
                ('codigo', models.CharField(max_length=10, null=True)),
                ('aporte', models.CharField(max_length=10, null=True)),
                ('pais', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='general.genpais')),
                ('tipo_persona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='general.gentipopersona')),
            ],
            options={
                'verbose_name': 'Identificación',
                'verbose_name_plural': 'Identificaciones',
                'db_table': 'gen_identificacion',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='genestado',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.genpais'),
        ),
        migrations.CreateModel(
            name='GenContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_identificacion', models.CharField(max_length=20)),
                ('digito_verificacion', models.CharField(max_length=1, null=True)),
                ('nombre_corto', models.CharField(max_length=200)),
                ('nombre1', models.CharField(max_length=50, null=True)),
                ('nombre2', models.CharField(max_length=50, null=True)),
                ('apellido1', models.CharField(max_length=50, null=True)),
                ('apellido2', models.CharField(max_length=50, null=True)),
                ('direccion', models.CharField(max_length=100)),
                ('barrio', models.CharField(max_length=200, null=True)),
                ('codigo_ciuu', models.CharField(max_length=200, null=True)),
                ('codigo_postal', models.CharField(max_length=20, null=True)),
                ('telefono', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=50, null=True)),
                ('correo', models.CharField(max_length=255)),
                ('correo_facturacion_electronica', models.CharField(max_length=255, null=True)),
                ('cliente', models.BooleanField(default=False)),
                ('proveedor', models.BooleanField(default=False)),
                ('empleado', models.BooleanField(default=False)),
                ('conductor', models.BooleanField(default=False)),
                ('numero_cuenta', models.CharField(max_length=50, null=True)),
                ('numero_licencia', models.CharField(max_length=50, null=True)),
                ('fecha_vence_licencia', models.DateField(null=True)),
                ('asesor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='general.genasesor')),
                ('banco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='general.genbanco')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.genciudad')),
                ('cuenta_banco_clase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='general.gencuentabancoclase')),
                ('identificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.genidentificacion')),
                ('plazo_pago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contactos_plazo_pago', to='general.genplazopago')),
                ('plazo_pago_proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contactos_plazo_pago_proveedor', to='general.genplazopago')),
                ('precio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='general.genprecio')),
                ('tipo_persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.gentipopersona')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'db_table': 'gen_contacto',
            },
        ),
    ]
