# Generated by Django 6.0.4 on 2026-05-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenDocumentoClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('grupo', models.IntegerField(null=True)),
                ('codigo_dian', models.CharField(default='01', max_length=2)),
            ],
            options={
                'verbose_name': 'Clase de documento',
                'verbose_name_plural': 'Clases de documento',
                'db_table': 'gen_documento_clase',
                'ordering': ['nombre'],
            },
        ),
    ]
