# Generated by Django 6.0.4 on 2026-05-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_agregar_documento_clase'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenResolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefijo', models.CharField(max_length=50, null=True)),
                ('numero', models.CharField(max_length=50, null=True)),
                ('clave_tecnica', models.CharField(max_length=500, null=True)),
                ('set_prueba', models.CharField(max_length=500, null=True)),
                ('consecutivo_desde', models.IntegerField()),
                ('consecutivo_hasta', models.IntegerField()),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
                ('venta', models.BooleanField(default=False)),
                ('compra', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Resolución',
                'verbose_name_plural': 'Resoluciones',
                'db_table': 'gen_resolucion',
                'ordering': ['numero'],
            },
        ),
    ]
