# Generated by Django 6.0.4 on 2026-05-13 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_agregar_comprobante'),
        ('general', '0003_agregar_resolucion'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenDocumentoTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('consecutivo', models.IntegerField(default=1)),
                ('venta', models.BooleanField(default=False)),
                ('compra', models.BooleanField(default=False)),
                ('cobrar', models.BooleanField(default=False)),
                ('pagar', models.BooleanField(default=False)),
                ('electronico', models.BooleanField(default=False)),
                ('contabilidad', models.BooleanField(default=False)),
                ('inventario', models.BooleanField(default=False)),
                ('pos', models.BooleanField(default=False)),
                ('operacion', models.BigIntegerField(default=0)),
                ('operacion_inventario', models.BigIntegerField(default=0)),
                ('operacion_remision', models.BigIntegerField(default=0)),
                ('afecta_cantidad', models.BooleanField(default=False)),
                ('comprobante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_tipos_comprobante_rel', to='contabilidad.concomprobante')),
                ('cuenta_cobrar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_tipos_cuenta_cobrar', to='contabilidad.concuenta')),
                ('cuenta_pagar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_tipos_cuenta_pagar', to='contabilidad.concuenta')),
                ('documento_clase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_tipos_documento_clase', to='general.gendocumentoclase')),
                ('resolucion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_tipos_resolucion', to='general.genresolucion')),
            ],
            options={
                'verbose_name': 'Tipo de documento',
                'verbose_name_plural': 'Tipos de documento',
                'db_table': 'gen_documento_tipo',
                'ordering': ['nombre'],
            },
        ),
    ]
