# Generated by Django 6.0.4 on 2026-05-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_agregar_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumento',
            name='horas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='gendocumento',
            name='horas_diurnas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='gendocumento',
            name='horas_nocturnas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
