# Generated by Django 6.0.4 on 2026-05-18 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_agregar_comprobante'),
        ('general', '0006_documento_add_horas'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenDocumentoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_registro', models.CharField(default='I', max_length=1)),
                ('cantidad', models.FloatField(default=0)),
                ('cantidad_operada', models.FloatField(default=0)),
                ('cantidad_afectada', models.FloatField(default=0)),
                ('cantidad_pendiente', models.FloatField(default=0)),
                ('costo', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('precio', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('pago', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('pago_operado', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('subtotal', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('descuento', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('total_bruto', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('base', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('base_impuesto', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('impuesto', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('impuesto_retencion', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('impuesto_operado', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('total', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('hora', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('dias', models.BigIntegerField(default=0)),
                ('base_cotizacion', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('base_prestacion', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('base_prestacion_vacacion', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('porcentaje', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('porcentaje_descuento', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('devengado', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('deduccion', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('naturaleza', models.CharField(max_length=1, null=True)),
                ('operacion', models.BigIntegerField(default=0)),
                ('operacion_inventario', models.BigIntegerField(default=0)),
                ('operacion_remision', models.BigIntegerField(default=0)),
                ('detalle', models.CharField(max_length=150, null=True)),
                ('numero', models.IntegerField(null=True)),
                ('contacto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_detalles_contacto_rel', to='general.gencontacto')),
                ('cuenta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_detalles_cuenta_rel', to='contabilidad.concuenta')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_detalles_documento_rel', to='general.gendocumento')),
                ('documento_afectado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_detalles_documento_afectado_rel', to='general.gendocumento')),
                ('documento_detalle_afectado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_detalles_documento_detalle_afectado_rel', to='general.gendocumentodetalle')),
            ],
            options={
                'verbose_name': 'Documento detalle',
                'verbose_name_plural': 'Documentos detalles',
                'db_table': 'gen_documento_detalle',
                'ordering': ['-id'],
            },
        ),
    ]
