# Generated by Django 6.0.4 on 2026-05-18 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_agregar_comprobante'),
        ('general', '0007_gendocumentodetalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=100, null=True)),
                ('referencia', models.CharField(max_length=50, null=True)),
                ('costo_promedio', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('costo_total', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('costo', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('precio', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('producto', models.BooleanField(default=False)),
                ('servicio', models.BooleanField(default=False)),
                ('inventario', models.BooleanField(default=False)),
                ('negativo', models.BooleanField(default=False)),
                ('favorito', models.BooleanField(default=False)),
                ('venta', models.BooleanField(default=True)),
                ('inactivo', models.BooleanField(default=False)),
                ('existencia', models.FloatField(default=0)),
                ('remision', models.FloatField(default=0)),
                ('disponible', models.FloatField(default=0)),
                ('imagen', models.TextField(null=True)),
                ('cuenta_compra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itemes_cuenta_compra_rel', to='contabilidad.concuenta')),
                ('cuenta_costo_venta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itemes_cuenta_costo_venta_rel', to='contabilidad.concuenta')),
                ('cuenta_inventario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itemes_cuenta_inventario_rel', to='contabilidad.concuenta')),
                ('cuenta_venta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itemes_cuenta_venta_rel', to='contabilidad.concuenta')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'db_table': 'gen_item',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_detalles_item_rel', to='general.genitem'),
        ),
    ]
