# Generated by Django 6.0.4 on 2026-05-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_genitem_gendocumentodetalle_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gendocumento',
            name='afectado',
            field=models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='gendocumento',
            name='base_cotizacion',
            field=models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='gendocumento',
            name='base_impuesto',
            field=models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='gendocumento',
            name='base_prestacion',
            field=models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='gendocumento',
            name='base_prestacion_vacacion',
            field=models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='gendocumento',
            name='deduccion',
            field=models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='gendocumento',
            name='descuento',
            field=models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='gendocumento',
            name='devengado',
            field=models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='gendocumento',
            name='dias',
            field=models.BigIntegerField(db_default=0, default=0),
        ),
        migrations.AlterField(
            model_name='gendocumento',
            name='estado_anulado',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='gendocumento',
            name='estado_aprobado',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='gendocumento',
            name='estado_contabilizado',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='gendocumento',
            name='estado_electronico',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='gendocumento',
            name='estado_electronico_descartado',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='gendocumento',
            name='estado_electronico_enviado',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='gendocumento',
            name='estado_electronico_evento',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='gendocumento',
            name='estado_electronico_notificado',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='gendocumento',
            name='evento_aceptacion',
            field=models.CharField(db_default='PE', default='PE', max_length=2),
        ),
        migrations.AlterField(
            model_name='gendocumento',
            name='evento_documento',
            field=models.CharField(db_default='PE', default='PE', max_length=2),
        ),
        migrations.AlterField(
            model_name='gendocumento',
            name='evento_recepcion',
            field=models.CharField(db_default='PE', default='PE', max_length=2),
        ),
        migrations.AlterField(
            model_name='gendocumento',
            name='guias',
            field=models.IntegerField(db_default=0, default=0),
        ),
        migrations.AlterField(
            model_name='gendocumento',
            name='horas',
            field=models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='gendocumento',
            name='horas_diurnas',
            field=models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='gendocumento',
            name='horas_nocturnas',
            field=models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='gendocumento',
            name='impuesto',
            field=models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='gendocumento',
            name='impuesto_operado',
            field=models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='gendocumento',
            name='impuesto_retencion',
            field=models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='gendocumento',
            name='pago',
            field=models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='gendocumento',
            name='pendiente',
            field=models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='gendocumento',
            name='provision_cesantia',
            field=models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='gendocumento',
            name='provision_interes',
            field=models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='gendocumento',
            name='provision_prima',
            field=models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='gendocumento',
            name='provision_vacacion',
            field=models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='gendocumento',
            name='salario',
            field=models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='gendocumento',
            name='subtotal',
            field=models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='gendocumento',
            name='total',
            field=models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='gendocumento',
            name='total_bruto',
            field=models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='gendocumentodetalle',
            name='base',
            field=models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='gendocumentodetalle',
            name='base_cotizacion',
            field=models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='gendocumentodetalle',
            name='base_impuesto',
            field=models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='gendocumentodetalle',
            name='base_prestacion',
            field=models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='gendocumentodetalle',
            name='base_prestacion_vacacion',
            field=models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='gendocumentodetalle',
            name='cantidad',
            field=models.FloatField(db_default=0, default=0),
        ),
        migrations.AlterField(
            model_name='gendocumentodetalle',
            name='cantidad_afectada',
            field=models.FloatField(db_default=0, default=0),
        ),
        migrations.AlterField(
            model_name='gendocumentodetalle',
            name='cantidad_operada',
            field=models.FloatField(db_default=0, default=0),
        ),
        migrations.AlterField(
            model_name='gendocumentodetalle',
            name='cantidad_pendiente',
            field=models.FloatField(db_default=0, default=0),
        ),
        migrations.AlterField(
            model_name='gendocumentodetalle',
            name='costo',
            field=models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='gendocumentodetalle',
            name='deduccion',
            field=models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='gendocumentodetalle',
            name='descuento',
            field=models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='gendocumentodetalle',
            name='devengado',
            field=models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='gendocumentodetalle',
            name='dias',
            field=models.BigIntegerField(db_default=0, default=0),
        ),
        migrations.AlterField(
            model_name='gendocumentodetalle',
            name='hora',
            field=models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='gendocumentodetalle',
            name='impuesto',
            field=models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='gendocumentodetalle',
            name='impuesto_operado',
            field=models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='gendocumentodetalle',
            name='impuesto_retencion',
            field=models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='gendocumentodetalle',
            name='operacion',
            field=models.BigIntegerField(db_default=0, default=0),
        ),
        migrations.AlterField(
            model_name='gendocumentodetalle',
            name='operacion_inventario',
            field=models.BigIntegerField(db_default=0, default=0),
        ),
        migrations.AlterField(
            model_name='gendocumentodetalle',
            name='operacion_remision',
            field=models.BigIntegerField(db_default=0, default=0),
        ),
        migrations.AlterField(
            model_name='gendocumentodetalle',
            name='pago',
            field=models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='gendocumentodetalle',
            name='pago_operado',
            field=models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='gendocumentodetalle',
            name='porcentaje',
            field=models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='gendocumentodetalle',
            name='porcentaje_descuento',
            field=models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='gendocumentodetalle',
            name='precio',
            field=models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='gendocumentodetalle',
            name='subtotal',
            field=models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='gendocumentodetalle',
            name='tipo_registro',
            field=models.CharField(db_default='I', default='I', max_length=1),
        ),
        migrations.AlterField(
            model_name='gendocumentodetalle',
            name='total',
            field=models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='gendocumentodetalle',
            name='total_bruto',
            field=models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='genitem',
            name='costo',
            field=models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='genitem',
            name='costo_promedio',
            field=models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='genitem',
            name='costo_total',
            field=models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='genitem',
            name='disponible',
            field=models.FloatField(db_default=0, default=0),
        ),
        migrations.AlterField(
            model_name='genitem',
            name='existencia',
            field=models.FloatField(db_default=0, default=0),
        ),
        migrations.AlterField(
            model_name='genitem',
            name='favorito',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='genitem',
            name='inactivo',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='genitem',
            name='inventario',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='genitem',
            name='negativo',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='genitem',
            name='precio',
            field=models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='genitem',
            name='producto',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='genitem',
            name='remision',
            field=models.FloatField(db_default=0, default=0),
        ),
        migrations.AlterField(
            model_name='genitem',
            name='servicio',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='genitem',
            name='venta',
            field=models.BooleanField(db_default=True, default=True),
        ),
    ]
