# Generated by Django 6.0.4 on 2026-05-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0009_alter_gendocumento_afectado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genciudad',
            name='porcentaje_impuesto',
            field=models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='gencontacto',
            name='cliente',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='gencontacto',
            name='conductor',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='gencontacto',
            name='empleado',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='gencontacto',
            name='proveedor',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='gendocumentoclase',
            name='codigo_dian',
            field=models.CharField(db_default='01', default='01', max_length=2),
        ),
        migrations.AlterField(
            model_name='gendocumentotipo',
            name='afecta_cantidad',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='gendocumentotipo',
            name='cobrar',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='gendocumentotipo',
            name='compra',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='gendocumentotipo',
            name='consecutivo',
            field=models.IntegerField(db_default=1, default=1),
        ),
        migrations.AlterField(
            model_name='gendocumentotipo',
            name='contabilidad',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='gendocumentotipo',
            name='electronico',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='gendocumentotipo',
            name='inventario',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='gendocumentotipo',
            name='operacion',
            field=models.BigIntegerField(db_default=0, default=0),
        ),
        migrations.AlterField(
            model_name='gendocumentotipo',
            name='operacion_inventario',
            field=models.BigIntegerField(db_default=0, default=0),
        ),
        migrations.AlterField(
            model_name='gendocumentotipo',
            name='operacion_remision',
            field=models.BigIntegerField(db_default=0, default=0),
        ),
        migrations.AlterField(
            model_name='gendocumentotipo',
            name='pagar',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='gendocumentotipo',
            name='pos',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='gendocumentotipo',
            name='venta',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='genidentificacion',
            name='orden',
            field=models.BigIntegerField(db_default=0, default=0),
        ),
        migrations.AlterField(
            model_name='genplazopago',
            name='dias',
            field=models.IntegerField(db_default=0, default=0),
        ),
        migrations.AlterField(
            model_name='genprecio',
            name='compra',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='genprecio',
            name='venta',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='genresolucion',
            name='compra',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='genresolucion',
            name='venta',
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
