# Generated by Django 6.0.4 on 2026-05-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0010_alter_genciudad_porcentaje_impuesto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenSector',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('porcentaje', models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=5)),
                ('tipo', models.CharField(choices=[('C', 'Comercial'), ('R', 'Residencial')], db_default='R', default='R', max_length=1)),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectores',
                'db_table': 'gen_sector',
                'ordering': ['nombre'],
            },
        ),
    ]
