# Generated by Django 6.0.4 on 2026-05-19 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0011_gensector'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumento',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_sector_rel', to='general.gensector'),
        ),
    ]
