# Generated by Django 6.0.4 on 2026-05-19 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0012_gendocumento_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumento',
            name='estrato',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
    ]
