# Generated by Django 6.0.4 on 2026-05-19 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0013_gendocumento_estrato'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenModalidad',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('codigo', models.CharField(max_length=10, null=True)),
                ('porcentaje_comercial', models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=5)),
                ('porcentaje_residencial', models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'verbose_name': 'Modalidad',
                'verbose_name_plural': 'Modalidades',
                'db_table': 'gen_modalidad',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='modalidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_detalles_modalidad_rel', to='general.genmodalidad'),
        ),
    ]
