# Generated by Django 6.0.4 on 2026-05-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0014_genmodalidad_gendocumentodetalle_modalidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='horas',
            field=models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='horas_diurnas',
            field=models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='horas_nocturnas',
            field=models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=10),
        ),
    ]
