# Generated by Django 6.0.4 on 2026-05-19 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0015_gendocumentodetalle_horas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumento',
            name='modalidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_modalidad_rel', to='general.genmodalidad'),
        ),
    ]
