# Generated by Django 6.0.4 on 2026-05-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0016_gendocumento_modalidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumento',
            name='domingo',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='gendocumento',
            name='festivo',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='gendocumento',
            name='hora_desde',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='gendocumento',
            name='hora_hasta',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='gendocumento',
            name='jueves',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='gendocumento',
            name='lunes',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='gendocumento',
            name='martes',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='gendocumento',
            name='miercoles',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='gendocumento',
            name='sabado',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='gendocumento',
            name='viernes',
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
