# Generated by Django 6.0.4 on 2026-05-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0017_gendocumento_domingo_gendocumento_festivo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gendocumento',
            name='domingo',
        ),
        migrations.RemoveField(
            model_name='gendocumento',
            name='festivo',
        ),
        migrations.RemoveField(
            model_name='gendocumento',
            name='hora_desde',
        ),
        migrations.RemoveField(
            model_name='gendocumento',
            name='hora_hasta',
        ),
        migrations.RemoveField(
            model_name='gendocumento',
            name='jueves',
        ),
        migrations.RemoveField(
            model_name='gendocumento',
            name='lunes',
        ),
        migrations.RemoveField(
            model_name='gendocumento',
            name='martes',
        ),
        migrations.RemoveField(
            model_name='gendocumento',
            name='miercoles',
        ),
        migrations.RemoveField(
            model_name='gendocumento',
            name='sabado',
        ),
        migrations.RemoveField(
            model_name='gendocumento',
            name='viernes',
        ),
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='domingo',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='festivo',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='hora_desde',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='hora_hasta',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='jueves',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='lunes',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='martes',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='miercoles',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='sabado',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='viernes',
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
