# Generated by Django 6.0.4 on 2026-05-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0018_remove_gendocumento_domingo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='compuesto',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='cortesia',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='programar',
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
