# Generated by Django 6.0.4 on 2026-05-22 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0019_gendocumentodetalle_compuesto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genprecio',
            options={'ordering': ['-id'], 'verbose_name': 'Precio', 'verbose_name_plural': 'Precios'},
        ),
    ]
