# Generated by Django 6.0.4 on 2026-05-22 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0020_alter_genprecio_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenPrecioDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vr_precio', models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=10)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='precios_detalles_item_rel', to='general.genitem')),
                ('precio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='general.genprecio')),
            ],
            options={
                'verbose_name': 'Precio detalle',
                'verbose_name_plural': 'Precios detalles',
                'db_table': 'gen_precio_detalle',
                'ordering': ['-id'],
            },
        ),
    ]
