# Generated by Django 6.0.4 on 2026-05-28 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0021_genpreciodetalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenAccion',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Acción',
                'verbose_name_plural': 'Acciones',
                'db_table': 'gen_accion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GenModelo',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=50)),
                ('clase', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('tabla', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
                'db_table': 'gen_modelo',
                'ordering': ['app', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='GenLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('objeto_id', models.CharField(db_index=True, max_length=50)),
                ('objeto_repr', models.CharField(max_length=255)),
                ('cambios', models.JSONField(null=True)),
                ('usuario_id', models.BigIntegerField(db_index=True, null=True)),
                ('usuario_correo', models.CharField(max_length=255, null=True)),
                ('accion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.genaccion')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.genmodelo')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
                'db_table': 'gen_log',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['modelo', 'objeto_id'], name='gen_log_modelo__b0317c_idx')],
            },
        ),
    ]
