# Generated by Django 6.0.4 on 2026-05-28 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0022_genaccion_genmodelo_genlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genlog',
            name='objeto_repr',
        ),
    ]
