# Generated by Django 6.0.4 on 2026-05-28 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0023_remove_genlog_objeto_repr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genlog',
            old_name='cambios',
            new_name='datos',
        ),
    ]
