# Generated by Django 6.0.4 on 2026-05-28 15:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0024_rename_cambios_genlog_datos'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenArchivoTipo',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo de archivo',
                'verbose_name_plural': 'Tipos de archivo',
                'db_table': 'gen_archivo_tipo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GenArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('objeto_id', models.CharField(db_index=True, max_length=50)),
                ('nombre', models.CharField(max_length=500)),
                ('tipo', models.CharField(max_length=100)),
                ('tamano', models.BigIntegerField(db_default=0, default=0)),
                ('almacenamiento_id', models.CharField(max_length=500)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('url', models.CharField(max_length=500, null=True)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.genmodelo')),
                ('archivo_tipo', models.ForeignKey(db_default=1, default=1, on_delete=django.db.models.deletion.PROTECT, to='general.genarchivotipo')),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
                'db_table': 'gen_archivo',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['modelo', 'objeto_id'], name='gen_archivo_modelo__4ac6a1_idx')],
            },
        ),
    ]
