# Generated by Django 6.0.4 on 2026-05-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0025_genarchivotipo_genarchivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='genmodelo',
            name='tipo',
            field=models.CharField(choices=[('A', 'Administrador'), ('M', 'Movimiento'), ('D', 'Detalle')], db_default='A', default='A', max_length=1),
        ),
    ]
