# Generated by Django 6.0.4 on 2026-05-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0026_genmodelo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genmodelo',
            name='tipo',
            field=models.CharField(choices=[('A', 'Administrador'), ('M', 'Movimiento'), ('D', 'Detalle'), ('F', 'Fixture')], db_default='A', default='A', max_length=1),
        ),
    ]
