# Generated by Django 6.0.4 on 2026-05-28 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0027_alter_genmodelo_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenResponsabilidad',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Responsabilidad',
                'verbose_name_plural': 'Responsabilidades',
                'db_table': 'gen_responsabilidad',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='gencontacto',
            name='responsabilidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='general.genresponsabilidad'),
        ),
    ]
