# Generated by Django 6.0.4 on 2026-05-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0028_genresponsabilidad_gencontacto_responsabilidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genresponsabilidad',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': 'Responsabilidad', 'verbose_name_plural': 'Responsabilidades'},
        ),
        migrations.AddField(
            model_name='genresponsabilidad',
            name='estado_activo',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='genresponsabilidad',
            name='orden',
            field=models.BigIntegerField(db_default=0, default=0),
        ),
    ]
