# Generated by Django 6.0.4 on 2026-05-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0029_alter_genresponsabilidad_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gencontacto',
            name='celular',
            field=models.CharField(db_default='', default='', max_length=50),
        ),
    ]
