# Generated by Django 6.0.4 on 2026-05-31 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0030_alter_gencontacto_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gendocumentodetalle',
            name='cantidad',
            field=models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='gendocumentodetalle',
            name='cantidad_afectada',
            field=models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='gendocumentodetalle',
            name='cantidad_operada',
            field=models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='gendocumentodetalle',
            name='cantidad_pendiente',
            field=models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20),
        ),
    ]
