# Generated by Django 6.0.4 on 2026-06-01 11:26

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0031_cantidad_floatfield_to_decimalfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genlog',
            name='datos',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
