# Generated by Django 6.0.4 on 2026-06-01 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0003_alter_concomprobante_permite_asiento_and_more'),
        ('general', '0032_alter_genlog_datos'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenImpuestoTipo',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Tipo de impuesto',
                'verbose_name_plural': 'Tipos de impuesto',
                'db_table': 'gen_impuesto_tipo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GenImpuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('nombre_extendido', models.CharField(max_length=100)),
                ('porcentaje', models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=10)),
                ('porcentaje_base', models.DecimalField(db_default=100, decimal_places=2, default=100, max_digits=10)),
                ('operacion', models.IntegerField(db_default=1, default=1)),
                ('venta', models.BooleanField(db_default=True, default=True)),
                ('compra', models.BooleanField(db_default=True, default=True)),
                ('cuenta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='impuestos_cuenta_rel', to='contabilidad.concuenta')),
                ('impuesto_tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='impuestos_impuesto_tipo_rel', to='general.genimpuestotipo')),
            ],
            options={
                'verbose_name': 'Impuesto',
                'verbose_name_plural': 'Impuestos',
                'db_table': 'gen_impuesto',
                'ordering': ['id', 'impuesto_tipo_id'],
            },
        ),
    ]
