# Generated by Django 6.0.4 on 2026-06-01 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0033_genimpuestotipo_genimpuesto'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenDocumentoImpuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20)),
                ('porcentaje', models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20)),
                ('porcentaje_base', models.DecimalField(db_default=100, decimal_places=6, default=100, max_digits=20)),
                ('total', models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20)),
                ('total_operado', models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20)),
                ('documento_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_impuestos_documento_detalle_rel', to='general.gendocumentodetalle')),
                ('impuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_impuestos_impuesto_rel', to='general.genimpuesto')),
            ],
            options={
                'verbose_name': 'Documento impuesto',
                'verbose_name_plural': 'Documentos impuestos',
                'db_table': 'gen_documento_impuesto',
                'ordering': ['-id'],
            },
        ),
    ]
