# Generated by Django 6.0.4 on 2026-06-02 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0034_gendocumentoimpuesto'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenItemImpuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_impuestos_impuesto_rel', to='general.genimpuesto')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_impuestos_item_rel', to='general.genitem')),
            ],
            options={
                'verbose_name': 'Item impuesto',
                'verbose_name_plural': 'Items impuestos',
                'db_table': 'gen_item_impuesto',
                'ordering': ['-id'],
                'unique_together': {('item', 'impuesto')},
            },
        ),
    ]
