# Generated by Django 6.0.4 on 2026-06-06 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0035_genitemimpuesto'),
        ('humano', '0008_humaporte_humaportecontrato_humaportedetalle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenConfiguracion',
            fields=[
                ('id', models.BigIntegerField(db_default=1, default=1, primary_key=True, serialize=False)),
                ('gen_uvt', models.DecimalField(db_default=49799, decimal_places=6, default=49799, max_digits=20)),
                ('hum_factor', models.DecimalField(db_default=7.666, decimal_places=3, default=7.666, max_digits=6)),
                ('hum_salario_minimo', models.DecimalField(db_default=1423500, decimal_places=6, default=1423500, max_digits=20)),
                ('hum_auxilio_transporte', models.DecimalField(db_default=200000, decimal_places=6, default=200000, max_digits=20)),
                ('hum_entidad_riesgo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuraciones_entidad_riesgo_rel', to='humano.humentidad')),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuraciones',
                'db_table': 'gen_configuracion',
            },
        ),
    ]
