# Generated by Django 6.0.4 on 2026-06-06 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0036_genconfiguracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='genconfiguracion',
            name='gen_empresa_ciudad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuraciones_empresa_ciudad_rel', to='general.genciudad'),
        ),
        migrations.AddField(
            model_name='genconfiguracion',
            name='gen_empresa_correo',
            field=models.EmailField(db_default='', default='', max_length=255),
        ),
        migrations.AddField(
            model_name='genconfiguracion',
            name='gen_empresa_digito_verificacion',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='genconfiguracion',
            name='gen_empresa_direccion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='genconfiguracion',
            name='gen_empresa_identificacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuraciones_empresa_identificacion_rel', to='general.genidentificacion'),
        ),
        migrations.AddField(
            model_name='genconfiguracion',
            name='gen_empresa_imagen',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='genconfiguracion',
            name='gen_empresa_nombre_corto',
            field=models.CharField(db_default='', default='', max_length=200),
        ),
        migrations.AddField(
            model_name='genconfiguracion',
            name='gen_empresa_numero_identificacion',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='genconfiguracion',
            name='gen_empresa_telefono',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='genconfiguracion',
            name='gen_empresa_tipo_persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuraciones_empresa_tipo_persona_rel', to='general.gentipopersona'),
        ),
    ]
