# Generated by Django 6.0.4 on 2026-06-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0037_genconfiguracion_gen_empresa_ciudad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='fecha_desde',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='fecha_hasta',
            field=models.DateField(null=True),
        ),
    ]
