# Generated by Django 6.0.4 on 2026-06-06 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0038_gendocumentodetalle_fecha_desde_and_more'),
        ('turno', '0003_turturno'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='puesto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_detalles_puesto_rel', to='turno.turpuesto'),
        ),
    ]
