# Generated by Django 6.0.4 on 2026-06-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0039_gendocumentodetalle_puesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='genmodalidad',
            name='orden',
            field=models.IntegerField(db_default=0, default=0),
        ),
    ]
