# Generated by Django 6.0.4 on 2026-06-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0040_genmodalidad_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genitem',
            name='disponible',
            field=models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='genitem',
            name='existencia',
            field=models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='genitem',
            name='remision',
            field=models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20),
        ),
    ]
