# Generated by Django 6.0.4 on 2026-06-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0041_alter_genitem_disponible_alter_genitem_existencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='precio_minimo',
            field=models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20),
        ),
    ]
