# Generated by Django 6.0.4 on 2026-06-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0042_gendocumentodetalle_precio_minimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genconfiguracion',
            name='gen_uvt',
            field=models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='genconfiguracion',
            name='hum_auxilio_transporte',
            field=models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='genconfiguracion',
            name='hum_factor',
            field=models.DecimalField(db_default=0, decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='genconfiguracion',
            name='hum_salario_minimo',
            field=models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20),
        ),
    ]
