# Generated by Django 6.0.4 on 2026-06-09 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0043_alter_genconfiguracion_gen_uvt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gendocumento',
            name='modalidad',
        ),
    ]
