# Generated by Django 6.0.4 on 2026-06-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0044_remove_gendocumento_modalidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='afectado',
            field=models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='pendiente',
            field=models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20),
        ),
    ]
