# Generated by Django 6.0.4 on 2026-06-11 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0045_gendocumentodetalle_afectado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gendocumentodetalle',
            name='documento_afectado',
        ),
    ]
