# Generated by Django 6.0.4 on 2026-06-11 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0046_remove_gendocumentodetalle_documento_afectado'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenFestivo',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(unique=True)),
                ('nombre', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Festivo',
                'verbose_name_plural': 'Festivos',
                'db_table': 'gen_festivo',
                'ordering': ['fecha'],
            },
        ),
    ]
