# Generated by Django 6.0.4 on 2026-06-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0047_genfestivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenMetodoPago',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Método de pago',
                'verbose_name_plural': 'Métodos de pago',
                'db_table': 'gen_metodo_pago',
                'ordering': ['nombre'],
            },
        ),
    ]
