# Generated by Django 6.0.4 on 2026-06-16 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0010_alter_concuenta_codigo'),
        ('general', '0048_genmetodopago'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenSede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=50, null=True)),
                ('centro_costo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sedes_centro_costo_rel', to='contabilidad.concentrocosto')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'db_table': 'gen_sede',
                'ordering': ['nombre'],
            },
        ),
    ]
