# Generated by Django 6.0.4 on 2026-06-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0049_gensede'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumentotipo',
            name='formato',
            field=models.CharField(choices=[('generico', 'Genérico')], db_default='generico', default='generico', max_length=20),
        ),
    ]
