# Generated by Django 6.0.4 on 2026-06-17 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0050_gendocumentotipo_formato'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumento',
            name='metodo_pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_metodo_pago_rel', to='general.genmetodopago'),
        ),
    ]
