# Generated by Django 6.0.4 on 2026-06-21 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0051_gendocumento_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumento',
            name='sede',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_sede_rel', to='general.gensede'),
        ),
    ]
