# Generated by Django 6.0.4 on 2026-06-22 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0013_concentrocosto_estado_inactivo'),
        ('general', '0052_gendocumento_sede'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenFormaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cuenta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='formas_pagos_cuenta_rel', to='contabilidad.concuenta')),
            ],
            options={
                'verbose_name': 'Forma de pago',
                'verbose_name_plural': 'Formas de pago',
                'db_table': 'gen_forma_pago',
                'ordering': ['id'],
            },
        ),
    ]
