# Generated by Django 6.0.4 on 2026-06-22 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0053_genformapago'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumento',
            name='forma_pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_forma_pago_rel', to='general.genformapago'),
        ),
    ]
