# Generated by Django 6.0.4 on 2026-06-24 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0054_gendocumento_forma_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumento',
            name='horas_diurnas_programadas',
            field=models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='gendocumento',
            name='horas_nocturnas_programadas',
            field=models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='gendocumento',
            name='horas_programadas',
            field=models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=10),
        ),
    ]
