# Generated by Django 6.0.4 on 2026-06-30 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0057_genpais_estado_inactivo_alter_genpais_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='documento_detalle_referencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_detalles_documento_detalle_referencia_rel', to='general.gendocumentodetalle'),
        ),
    ]
