# Generated by Django 6.0.4 on 2026-07-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0057_genpais_estado_inactivo_alter_genpais_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='generado',
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
