# Generated by Django 5.2.13 on 2026-08-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0059_content_type_solo_publico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genmodelo',
            name='tipo',
            field=models.CharField(choices=[('A', 'Administrador'), ('M', 'Movimiento'), ('D', 'Detalle'), ('F', 'Fixture'), ('S', 'Soporte')], db_default='A', default='A', max_length=1),
        ),
    ]
