# Generated by Django 5.2.13 on 2026-08-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0060_alter_genmodelo_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenParametro',
            fields=[
                ('id', models.BigIntegerField(db_default=1, default=1, primary_key=True, serialize=False)),
                ('gen_factura_electronica_activa', models.BooleanField(db_default=False, default=False)),
            ],
            options={
                'verbose_name': 'Parámetro',
                'verbose_name_plural': 'Parámetros',
                'db_table': 'gen_parametro',
            },
        ),
    ]
