# Generated by Django 5.2.13 on 2026-08-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0061_genparametro'),
    ]

    operations = [
        migrations.AddField(
            model_name='genconfiguracion',
            name='gen_empresa_razon_social',
            field=models.CharField(db_default='', default='', max_length=450),
        ),
        migrations.AddField(
            model_name='genparametro',
            name='gen_factura_electronica_emisor',
            field=models.BigIntegerField(null=True),
        ),
    ]
