# Generated by Django 5.2.13 on 2026-08-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0062_genconfiguracion_gen_empresa_razon_social_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genparametro',
            name='gen_certificado_vence',
            field=models.DateField(null=True),
        ),
    ]
