# Generated by Django 5.2.13 on 2026-09-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0064_genpreciodetalle_item_obligatorio_y_unico'),
    ]

    operations = [
        migrations.AddField(
            model_name='genparametro',
            name='gen_asistente_datos_iniciales',
            field=models.BooleanField(db_default=True, default=True),
        ),
    ]
