# Generated by Django 5.2.13 on 2026-09-03 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0014_alter_conperiodo_anio_alter_conperiodo_id_and_more'),
        ('general', '0066_alter_gencontacto_celular'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumento',
            name='centro_costo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_centro_costo_rel', to='contabilidad.concentrocosto'),
        ),
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='centro_costo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_detalles_centro_costo_rel', to='contabilidad.concentrocosto'),
        ),
    ]
