# Generated by Django 5.2.13 on 2026-09-04 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0067_gendocumento_centro_costo_and_more'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='almacen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_detalles_almacen_rel', to='inventario.invalmacen'),
        ),
    ]
