# Generated by Django 5.2.13 on 2026-09-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0068_gendocumentodetalle_almacen'),
    ]

    operations = [
        migrations.AddField(
            model_name='genconfiguracion',
            name='gen_emitir_automaticamente',
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
