# Generated by Django 5.2.13 on 2026-09-05 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0069_genconfiguracion_gen_emitir_automaticamente'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenDocumentoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pago', models.DecimalField(db_default=0, decimal_places=6, default=0, max_digits=20)),
                ('estado_anulado', models.BooleanField(db_default=False, default=False)),
                ('cuenta_banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_pagos_cuenta_banco', to='general.gencuentabanco')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_pagos_documento', to='general.gendocumento')),
            ],
            options={
                'verbose_name': 'Documento pago',
                'verbose_name_plural': 'Documentos pagos',
                'db_table': 'gen_documento_pago',
                'ordering': ['-id'],
            },
        ),
    ]
