# Generated by Django 5.2.13 on 2026-09-05 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0016_consaldocuenta'),
        ('general', '0070_gendocumentopago'),
        ('humano', '0009_humcontrato_habilitado_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumento',
            name='contrato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_contrato_rel', to='humano.humcontrato'),
        ),
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='activo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_detalles_activo_rel', to='contabilidad.conactivo'),
        ),
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='concepto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_detalles_concepto_rel', to='humano.humconcepto'),
        ),
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='contrato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_detalles_contrato_rel', to='humano.humcontrato'),
        ),
    ]
