# Generated by Django 5.2.13 on 2026-09-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0072_rename_usuario_correo_genlog_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='genconfiguracion',
            name='gen_empresa_logotipo',
            field=models.TextField(null=True),
        ),
    ]
