# Generated by Django 5.2.13 on 2026-09-10 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0073_genconfiguracion_gen_empresa_logotipo'),
        ('inventario', '0002_invexistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumento',
            name='almacen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_almacen_rel', to='inventario.invalmacen'),
        ),
    ]
