# Generated by Django 5.2.13 on 2026-09-10 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0074_gendocumento_almacen'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='documento_afectado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_detalles_documento_afectado_rel', to='general.gendocumento'),
        ),
    ]
