# Generated by Django 5.2.13 on 2026-09-10 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0075_gendocumentodetalle_documento_afectado'),
        ('humano', '0011_alter_humcontrato_centro_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='credito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_detalles_credito_rel', to='humano.humcredito'),
        ),
    ]
