# Generated by Django 5.2.13 on 2026-09-21 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0076_gendocumentodetalle_credito'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genparametro',
            old_name='gen_factura_electronica_emisor',
            new_name='gen_rededoc_emisor',
        ),
    ]
