# Generated by Django 5.2.13 on 2026-09-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0077_rename_emisor_gen_rededoc_emisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumentotipo',
            name='codigo',
            field=models.IntegerField(null=True),
        ),
    ]
