# Generated by Django 5.2.13 on 2026-10-02 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0080_genmodelo_tipo_catalogo'),
        ('humano', '0011_alter_humcontrato_centro_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumento',
            name='programacion_detalle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_programacion_detalle_rel', to='humano.humprogramaciondetalle'),
        ),
        migrations.AddField(
            model_name='gendocumentodetalle',
            name='novedad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_detalles_novedad_rel', to='humano.humnovedad'),
        ),
    ]
