# Generated by Django 5.2.13 on 2026-10-02 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0081_gendocumento_programacion_detalle_and_more'),
        ('humano', '0011_alter_humcontrato_centro_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='genconfiguracion',
            name='hum_licencia_no_remunerada_afecta_pension',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='gendocumento',
            name='aporte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_aporte_rel', to='humano.humaporte'),
        ),
    ]
