# Generated by Django 5.2.13 on 2026-10-02 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0082_aporte_documento_y_licencia_pension'),
        ('humano', '0011_alter_humcontrato_centro_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendocumento',
            name='liquidacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_liquidacion_rel', to='humano.humliquidacion'),
        ),
    ]
