# Generated by Django 5.2.13 on 2026-10-08 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0083_documento_liquidacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='genparametro',
            name='gen_electronico_habilitado_equivalente',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='genparametro',
            name='gen_electronico_habilitado_facturacion',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='genparametro',
            name='gen_electronico_habilitado_nomina',
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
