# Generated by Django 5.2.13 on 2026-10-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0086_parametro_asistente_electronico_venta_nomina'),
    ]

    operations = [
        migrations.AddField(
            model_name='genconfiguracion',
            name='ven_factura_informacion_inferior',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='genconfiguracion',
            name='ven_factura_informacion_superior',
            field=models.TextField(null=True),
        ),
    ]
