# Generated by Django 5.2.13 on 2026-10-08 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0087_configuracion_factura_informacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='genconfiguracion',
            name='ven_item_administracion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuraciones_item_administracion_rel', to='general.genitem'),
        ),
        migrations.AddField(
            model_name='genconfiguracion',
            name='ven_item_imprevisto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuraciones_item_imprevisto_rel', to='general.genitem'),
        ),
        migrations.AddField(
            model_name='genconfiguracion',
            name='ven_item_utilidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuraciones_item_utilidad_rel', to='general.genitem'),
        ),
    ]
