from .archivo import GenArchivoViewSet
from .asesor import GenAsesorViewSet
from .banco import GenBancoViewSet
from .ciudad import GenCiudadViewSet
from .configuracion import GenConfiguracionViewSet
from .contacto import GenContactoViewSet
from .cuenta_banco import GenCuentaBancoViewSet
from .cuenta_banco_clase import GenCuentaBancoClaseViewSet
from .cuenta_banco_tipo import GenCuentaBancoTipoViewSet
from .documento import GenDocumentoViewSet
from .documento_clase import GenDocumentoClaseViewSet
from .documento_detalle import GenDocumentoDetalleViewSet
from .documento_detalle_informe import GenDocumentoDetalleInformeViewSet
from .documento_informe import GenDocumentoInformeViewSet
from .documento_tipo import GenDocumentoTipoViewSet
from .estado import GenEstadoViewSet
from .festivo import GenFestivoViewSet
from .forma_pago import GenFormaPagoViewSet
from .identificacion import GenIdentificacionViewSet
from .impuesto import GenImpuestoViewSet
from .impuesto_tipo import GenImpuestoTipoViewSet
from .item import GenItemViewSet
from .log import GenLogViewSet
from .metodo_pago import GenMetodoPagoViewSet
from .modalidad import GenModalidadViewSet
from .modelo import GenModeloViewSet
from .pais import GenPaisViewSet
from .plazo_pago import GenPlazoPagoViewSet
from .precio import GenPrecioViewSet
from .prueba import PruebaView
from .resolucion import GenResolucionViewSet
from .responsabilidad import GenResponsabilidadViewSet
from .sector import GenSectorViewSet
from .sede import GenSedeViewSet
from .tipo_persona import GenTipoPersonaViewSet
