from .asesor import GenAsesorViewSet
from .banco import GenBancoViewSet
from .ciudad import GenCiudadViewSet
from .contacto import GenContactoViewSet
from .cuenta_banco_clase import GenCuentaBancoClaseViewSet
from .documento import GenDocumentoViewSet
from .plazo_pago import GenPlazoPagoViewSet
from .prueba import PruebaView
from .tipo_persona import GenTipoPersonaViewSet
