from .archivo import GenArchivoViewSet
from .asesor import GenAsesorViewSet
from .banco import GenBancoViewSet
from .ciudad import GenCiudadViewSet
from .contacto import GenContactoViewSet
from .cuenta_banco_clase import GenCuentaBancoClaseViewSet
from .documento import GenDocumentoViewSet
from .identificacion import GenIdentificacionViewSet
from .log import GenLogViewSet
from .plazo_pago import GenPlazoPagoViewSet
from .precio import GenPrecioViewSet
from .prueba import PruebaView
from .responsabilidad import GenResponsabilidadViewSet
from .tipo_persona import GenTipoPersonaViewSet
