# Generated by Django 6.0.4 on 2026-04-27 13:33

import tenant_users.permissions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email Address')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified')),
                ('username', models.EmailField(max_length=255, unique=True)),
                ('correo', models.EmailField(max_length=255, unique=True)),
                ('nombre_corto', models.CharField(max_length=255, null=True)),
                ('numero_identificacion', models.CharField(max_length=20, null=True)),
                ('celular', models.CharField(max_length=50, null=True)),
                ('idioma', models.CharField(default='es', max_length=2)),
                ('imagen', models.TextField(null=True)),
                ('imagen_thumbnail', models.TextField(null=True)),
                ('activo', models.BooleanField(default=True)),
                ('verificado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('tenants', models.ManyToManyField(blank=True, help_text='The tenants this user belongs to.', related_name='user_set', to='contenedor.ctncliente', verbose_name='tenants')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'seg_usuario',
            },
            bases=(models.Model, tenant_users.permissions.models.PermissionsMixinFacade),
        ),
    ]
