# Generated by Django 6.0.4 on 2026-04-27 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segusuario',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='segusuario',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='segusuario',
            name='username',
        ),
        migrations.RemoveField(
            model_name='segusuario',
            name='verificado',
        ),
    ]
