# Generated by Django 6.0.4 on 2026-05-01 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0003_alter_ctncliente_owner'),
        ('seguridad', '0002_remove_segusuario_activo_remove_segusuario_correo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('modulo', models.CharField(db_index=True, max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'db_table': 'seg_permiso',
                'ordering': ['modulo', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='SegRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'seg_rol',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SegRolPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso', models.ForeignKey(db_column='permiso_id', on_delete=django.db.models.deletion.CASCADE, related_name='rol_permisos', to='seguridad.segpermiso')),
                ('rol', models.ForeignKey(db_column='rol_id', on_delete=django.db.models.deletion.CASCADE, related_name='rol_permisos', to='seguridad.segrol')),
            ],
            options={
                'verbose_name': 'Rol-Permiso',
                'verbose_name_plural': 'Rol-Permisos',
                'db_table': 'seg_rol_permiso',
                'unique_together': {('rol', 'permiso')},
            },
        ),
        migrations.AddField(
            model_name='segrol',
            name='permisos',
            field=models.ManyToManyField(blank=True, related_name='roles', through='seguridad.SegRolPermiso', to='seguridad.segpermiso'),
        ),
        migrations.CreateModel(
            name='SegUsuarioRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='seguridad.segrol')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_rol', to='contenedor.ctncliente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_rol', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rol de Usuario',
                'verbose_name_plural': 'Roles de Usuarios',
                'db_table': 'seg_usuario_rol',
                'indexes': [models.Index(fields=['usuario', 'tenant'], name='seg_usuario_usuario_5bc2bd_idx')],
                'unique_together': {('usuario', 'rol', 'tenant')},
            },
        ),
    ]
