# Generated by Django 6.0.4 on 2026-05-01 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0003_alter_ctncliente_owner'),
        ('seguridad', '0003_segpermiso_segrol_segrolpermiso_segrol_permisos_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql='DROP TABLE IF EXISTS seg_usuario_tenants CASCADE;',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='segusuario',
                    name='tenants',
                    field=models.ManyToManyField(
                        blank=True,
                        related_name='user_set',
                        through='seguridad.SegUsuarioTenant',
                        to='contenedor.ctncliente',
                    ),
                ),
            ],
            database_operations=[],
        ),
        migrations.CreateModel(
            name='SegUsuarioTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.CASCADE, to='contenedor.ctncliente')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario-Tenant',
                'verbose_name_plural': 'Usuario-Tenants',
                'db_table': 'seg_usuario_tenants',
                'unique_together': {('usuario', 'cliente')},
            },
        ),
    ]
