# Generated by Django 6.0.4 on 2026-05-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0004_segusuariotenant_alter_segusuario_tenants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segusuario',
            name='imagen',
            field=models.TextField(default='usuarios/imagen_defecto.jpg'),
        ),
    ]
