# Generated by Django 6.0.4 on 2026-05-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0005_imagen_defecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segusuario',
            name='imagen_thumbnail',
            field=models.TextField(default='usuarios/imagen_defecto.jpg'),
        ),
    ]
