# Generated by Django 6.0.4 on 2026-05-05 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0006_imagen_thumbnail_defecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='segusuario',
            name='saldo_pendiente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
