# Generated by Django 6.0.4 on 2026-05-13 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0030_movimiento_add_contacto'),
        ('seguridad', '0007_billing_usuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SegUsuarioTenant',
            new_name='SegUsuarioCliente',
        ),
        migrations.AlterModelOptions(
            name='segusuariocliente',
            options={'verbose_name': 'Usuario-Cliente', 'verbose_name_plural': 'Usuario-Clientes'},
        ),
        migrations.AlterModelTable(
            name='segusuariocliente',
            table='seg_usuario_cliente',
        ),
    ]
