# Generated by Django 6.0.4 on 2026-05-14 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0008_rename_usuario_tenant_a_usuario_cliente'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='segusuariorol',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='segusuariorol',
            name='seg_usuario_usuario_5bc2bd_idx',
        ),
        migrations.AddField(
            model_name='segusuariocliente',
            name='rol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membresias', to='seguridad.segrol'),
        ),
        migrations.AlterField(
            model_name='segusuariocliente',
            name='usuario',
            field=models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='SegUsuarioRol',
        ),
    ]
