# Generated by Django 6.0.4 on 2026-05-14 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0009_usuario_cliente_add_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='segrol',
            name='codigo',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
