# Generated by Django 6.0.4 on 2026-05-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0010_rol_add_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segrol',
            name='activo',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AlterField(
            model_name='segusuario',
            name='idioma',
            field=models.CharField(db_default='es', default='es', max_length=2),
        ),
        migrations.AlterField(
            model_name='segusuario',
            name='imagen',
            field=models.TextField(db_default='usuarios/imagen_defecto.jpg', default='usuarios/imagen_defecto.jpg'),
        ),
        migrations.AlterField(
            model_name='segusuario',
            name='imagen_thumbnail',
            field=models.TextField(db_default='usuarios/imagen_defecto.jpg', default='usuarios/imagen_defecto.jpg'),
        ),
        migrations.AlterField(
            model_name='segusuario',
            name='saldo_pendiente',
            field=models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=14),
        ),
    ]
