# Generated by Django 5.2.13 on 2026-08-04 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0012_token_blacklist_cascade'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='segrolpermiso',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='segrolpermiso',
            name='permiso',
        ),
        migrations.RemoveField(
            model_name='segrol',
            name='permisos',
        ),
        migrations.RemoveField(
            model_name='segrolpermiso',
            name='rol',
        ),
        migrations.DeleteModel(
            name='SegPermiso',
        ),
        migrations.DeleteModel(
            name='SegRolPermiso',
        ),
    ]
