# Generated by Django 5.2.13 on 2026-08-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0013_remove_segrolpermiso_permiso_remove_segrol_permisos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='segusuariocliente',
            name='acceso_cartera',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='segusuariocliente',
            name='acceso_compra',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='segusuariocliente',
            name='acceso_contabilidad',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='segusuariocliente',
            name='acceso_humano',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='segusuariocliente',
            name='acceso_inventario',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='segusuariocliente',
            name='acceso_tesoreria',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='segusuariocliente',
            name='acceso_venta',
            field=models.BooleanField(db_default=True, default=True),
        ),
    ]
