# Generated by Django 5.2.13 on 2026-08-08 09:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0016_remove_segusuariocliente_rol_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegMfaCodigoRespaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_codigo', models.CharField(db_index=True, max_length=64)),
                ('usado_en', models.DateTimeField(null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='codigos_respaldo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Código de respaldo MFA',
                'verbose_name_plural': 'Códigos de respaldo MFA',
                'db_table': 'seg_mfa_codigo_respaldo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SegMfaDesafio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metodo', models.CharField(choices=[('totp', 'App autenticadora'), ('correo', 'Código por correo')], max_length=10)),
                ('hash_codigo', models.CharField(max_length=64, null=True)),
                ('expira', models.DateTimeField(db_index=True)),
                ('consumido', models.BooleanField(db_default=False, default=False)),
                ('intentos', models.PositiveSmallIntegerField(db_default=0, default=0)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='desafios_mfa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Desafío MFA',
                'verbose_name_plural': 'Desafíos MFA',
                'db_table': 'seg_mfa_desafio',
            },
        ),
        migrations.CreateModel(
            name='SegMfaDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_token', models.CharField(max_length=64, unique=True)),
                ('user_agent', models.TextField(null=True)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('ultimo_uso', models.DateTimeField(null=True)),
                ('expira', models.DateTimeField(db_index=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos_mfa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dispositivo MFA',
                'verbose_name_plural': 'Dispositivos MFA',
                'db_table': 'seg_mfa_dispositivo',
                'ordering': ['-ultimo_uso'],
            },
        ),
        migrations.CreateModel(
            name='SegMfaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('totp', 'App autenticadora'), ('correo', 'Código por correo')], db_default='totp', default='totp', max_length=10)),
                ('secreto', models.TextField(null=True)),
                ('activo', models.BooleanField(db_default=False, default=False)),
                ('ultimo_contador', models.BigIntegerField(null=True)),
                ('fecha_activacion', models.DateTimeField(null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='mfa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MFA de usuario',
                'verbose_name_plural': 'MFA de usuarios',
                'db_table': 'seg_mfa_usuario',
            },
        ),
    ]
