# Generated by Django 5.2.13 on 2026-08-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0017_mfa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmfadesafio',
            name='metodo',
            field=models.CharField(choices=[('sms', 'Código por SMS'), ('correo', 'Código por correo'), ('totp', 'App autenticadora')], max_length=10),
        ),
        migrations.AlterField(
            model_name='segmfausuario',
            name='metodo',
            field=models.CharField(choices=[('sms', 'Código por SMS'), ('correo', 'Código por correo'), ('totp', 'App autenticadora')], db_default='sms', default='sms', max_length=10),
        ),
    ]
