# Generated by Django 5.2.13 on 2026-08-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0018_mfa_sms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmfadesafio',
            name='metodo',
            field=models.CharField(choices=[('correo', 'Código por correo'), ('sms', 'Código por SMS'), ('totp', 'App autenticadora')], max_length=10),
        ),
        migrations.AlterField(
            model_name='segmfausuario',
            name='metodo',
            field=models.CharField(choices=[('correo', 'Código por correo'), ('sms', 'Código por SMS'), ('totp', 'App autenticadora')], db_default='sms', default='sms', max_length=10),
        ),
    ]
