# Generated by Django 5.2.13 on 2026-08-11 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0019_alter_segmfadesafio_metodo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=254)),
                ('resultado', models.CharField(choices=[('ok', 'Ingreso exitoso'), ('clave', 'Credenciales inválidas'), ('no_verificado', 'Cuenta no verificada'), ('mfa_pendiente', 'Segundo factor pendiente'), ('mfa_fallido', 'Segundo factor fallido')], db_index=True, max_length=20)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('user_agent', models.TextField(null=True)),
                ('metodo_mfa', models.CharField(max_length=10, null=True)),
                ('dispositivo_recordado', models.BooleanField(db_default=False, default=False)),
                ('codigo_respaldo', models.BooleanField(db_default=False, default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(db_column='usuario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acceso',
                'verbose_name_plural': 'Accesos',
                'db_table': 'seg_acceso',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['usuario', '-fecha'], name='seg_acceso_usuario_fecha'), models.Index(fields=['email', '-fecha'], name='seg_acceso_email_fecha'), models.Index(fields=['ip', '-fecha'], name='seg_acceso_ip_fecha')],
            },
        ),
    ]
