# Generated by Django 5.2.13 on 2026-08-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0020_acceso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segusuario',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='segusuario',
            name='imagen_thumbnail',
        ),
        migrations.AddField(
            model_name='segusuario',
            name='imagen_uuid',
            field=models.UUIDField(null=True),
        ),
    ]
