from .ciudad import CtnCiudadViewSet
from .cliente import CtnClienteViewSet
from .contacto import CtnContactoViewSet
from .estado import CtnEstadoViewSet
from .evento_pago import CtnEventoPagoViewSet
from .identificacion import CtnIdentificacionViewSet
from .invitacion import CtnInvitacionViewSet
from .movimiento import CtnMovimientoViewSet
from .pais import CtnPaisViewSet
from .rededoc import CtnRededocViewSet
from .suscripcion import CtnSuscripcionViewSet
from .suscripcion_tipo import CtnSuscripcionTipoViewSet
