from .ciudad import CtnCiudadViewSet
from .cliente import CtnClienteViewSet
from .contacto import CtnContactoViewSet
from .estado import CtnEstadoViewSet
from .identificacion import CtnIdentificacionViewSet
from .movimiento import CtnMovimientoViewSet
from .pais import CtnPaisViewSet
from .suscripcion import CtnSuscripcionViewSet
from .suscripcion_tipo import CtnSuscripcionTipoViewSet
from .evento_pago import CtnEventoPagoViewSet
