# Generated by Django 6.0.4 on 2026-06-02 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TurProgramador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estado_inactivo', models.BooleanField(db_default=False, default=False)),
            ],
            options={
                'verbose_name': 'Programador',
                'verbose_name_plural': 'Programadores',
                'db_table': 'tur_programador',
                'ordering': ['nombre'],
            },
        ),
    ]
