# Generated by Django 6.0.4 on 2026-06-02 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0006_alter_concentrocosto_codigo'),
        ('general', '0035_genitemimpuesto'),
        ('turno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurPuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=100, null=True)),
                ('celular', models.CharField(max_length=50, null=True)),
                ('latitud', models.DecimalField(decimal_places=8, max_digits=11, null=True)),
                ('longitud', models.DecimalField(decimal_places=8, max_digits=11, null=True)),
                ('comentario', models.TextField(null=True)),
                ('estado_inactivo', models.BooleanField(db_default=False, default=False)),
                ('centro_costo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='puestos_centro_costo_rel', to='contabilidad.concentrocosto')),
                ('ciudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='puestos_ciudad_rel', to='general.genciudad')),
                ('contacto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='puestos_contacto_rel', to='general.gencontacto')),
                ('programador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='puestos_programador_rel', to='turno.turprogramador')),
            ],
            options={
                'verbose_name': 'Puesto',
                'verbose_name_plural': 'Puestos',
                'db_table': 'tur_puesto',
                'ordering': ['nombre'],
            },
        ),
    ]
