# Generated by Django 6.0.4 on 2026-06-04 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turno', '0002_turpuesto'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('horas', models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=5)),
                ('horas_diurnas', models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=5)),
                ('horas_nocturnas', models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=5)),
                ('color', models.CharField(max_length=7, null=True)),
                ('estado_inactivo', models.BooleanField(db_default=False, default=False)),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'db_table': 'tur_turno',
                'ordering': ['nombre'],
            },
        ),
    ]
