# Generated by Django 6.0.4 on 2026-06-11 23:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turno', '0003_turturno'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurSecuencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, null=True)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('dia_1', models.CharField(max_length=10, null=True)),
                ('dia_2', models.CharField(max_length=10, null=True)),
                ('dia_3', models.CharField(max_length=10, null=True)),
                ('dia_4', models.CharField(max_length=10, null=True)),
                ('dia_5', models.CharField(max_length=10, null=True)),
                ('dia_6', models.CharField(max_length=10, null=True)),
                ('dia_7', models.CharField(max_length=10, null=True)),
                ('dia_8', models.CharField(max_length=10, null=True)),
                ('dia_9', models.CharField(max_length=10, null=True)),
                ('dia_10', models.CharField(max_length=10, null=True)),
                ('dia_11', models.CharField(max_length=10, null=True)),
                ('dia_12', models.CharField(max_length=10, null=True)),
                ('dia_13', models.CharField(max_length=10, null=True)),
                ('dia_14', models.CharField(max_length=10, null=True)),
                ('dia_15', models.CharField(max_length=10, null=True)),
                ('dia_16', models.CharField(max_length=10, null=True)),
                ('dia_17', models.CharField(max_length=10, null=True)),
                ('dia_18', models.CharField(max_length=10, null=True)),
                ('dia_19', models.CharField(max_length=10, null=True)),
                ('dia_20', models.CharField(max_length=10, null=True)),
                ('dia_21', models.CharField(max_length=10, null=True)),
                ('dia_22', models.CharField(max_length=10, null=True)),
                ('dia_23', models.CharField(max_length=10, null=True)),
                ('dia_24', models.CharField(max_length=10, null=True)),
                ('dia_25', models.CharField(max_length=10, null=True)),
                ('dia_26', models.CharField(max_length=10, null=True)),
                ('dia_27', models.CharField(max_length=10, null=True)),
                ('dia_28', models.CharField(max_length=10, null=True)),
                ('dia_29', models.CharField(max_length=10, null=True)),
                ('dia_30', models.CharField(max_length=10, null=True)),
                ('dia_31', models.CharField(max_length=10, null=True)),
                ('lunes', models.CharField(max_length=10, null=True)),
                ('martes', models.CharField(max_length=10, null=True)),
                ('miercoles', models.CharField(max_length=10, null=True)),
                ('jueves', models.CharField(max_length=10, null=True)),
                ('viernes', models.CharField(max_length=10, null=True)),
                ('sabado', models.CharField(max_length=10, null=True)),
                ('domingo', models.CharField(max_length=10, null=True)),
                ('festivo', models.CharField(max_length=10, null=True)),
                ('domingo_festivo', models.CharField(max_length=10, null=True)),
                ('horas', models.IntegerField(db_default=0, default=0)),
                ('dias', models.IntegerField(db_default=0, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)])),
                ('homologar', models.BooleanField(db_default=False, default=False)),
                ('estado_inactivo', models.BooleanField(db_default=False, default=False)),
            ],
            options={
                'verbose_name': 'Secuencia',
                'verbose_name_plural': 'Secuencias',
                'db_table': 'tur_secuencia',
                'ordering': ['nombre'],
            },
        ),
    ]
