# Generated by Django 6.0.4 on 2026-06-11 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0046_remove_gendocumentodetalle_documento_afectado'),
        ('humano', '0008_humaporte_humaportecontrato_humaportedetalle_and_more'),
        ('turno', '0004_tursecuencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurProgramacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('horas', models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=5)),
                ('horas_diurnas', models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=5)),
                ('horas_nocturnas', models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=5)),
                ('festivo', models.BooleanField(db_default=False, default=False)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programaciones_contrato_rel', to='humano.humcontrato')),
                ('documento_detalle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programaciones_documento_detalle_rel', to='general.gendocumentodetalle')),
                ('turno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programaciones_turno_rel', to='turno.turturno')),
            ],
            options={
                'verbose_name': 'Programación',
                'verbose_name_plural': 'Programaciones',
                'db_table': 'tur_programacion',
                'ordering': ['fecha', 'id'],
                'constraints': [models.UniqueConstraint(fields=('contrato', 'fecha'), name='uniq_programacion_contrato_fecha')],
            },
        ),
    ]
