# Generated by Django 6.0.4 on 2026-06-13 13:54

import django.db.models.deletion
import django.db.models.functions.datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0047_genfestivo'),
        ('turno', '0005_turprogramacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurPrototipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), default=django.utils.timezone.now)),
                ('fecha_inicio', models.DateField()),
                ('documento_detalle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prototipos_documento_detalle_rel', to='general.gendocumentodetalle')),
                ('secuencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prototipos_secuencia_rel', to='turno.tursecuencia')),
            ],
            options={
                'verbose_name': 'Prototipo',
                'verbose_name_plural': 'Prototipos',
                'db_table': 'tur_prototipo',
                'ordering': ['fecha', 'id'],
            },
        ),
    ]
