# Generated by Django 6.0.4 on 2026-06-13 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turno', '0006_turprototipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurProgramacionSimulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('horas', models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=5)),
                ('horas_diurnas', models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=5)),
                ('horas_nocturnas', models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=5)),
                ('festivo', models.BooleanField(db_default=False, default=False)),
                ('turno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programaciones_simulacion_turno_rel', to='turno.turturno')),
            ],
            options={
                'verbose_name': 'Programación simulación',
                'verbose_name_plural': 'Programaciones simulación',
                'db_table': 'tur_programacion_simulacion',
                'ordering': ['fecha', 'id'],
            },
        ),
    ]
