# Generated by Django 6.0.4 on 2026-06-13 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0008_humaporte_humaportecontrato_humaportedetalle_and_more'),
        ('turno', '0007_turprogramacionsimulacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
                ('fecha_hasta_periodo', models.DateField()),
                ('grupo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='soportes_grupo_rel', to='humano.humgrupo')),
            ],
            options={
                'verbose_name': 'Soporte',
                'verbose_name_plural': 'Soportes',
                'db_table': 'tur_soporte',
                'ordering': ['fecha_desde', 'id'],
            },
        ),
    ]
