# Generated by Django 6.0.4 on 2026-06-13 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0008_humaporte_humaportecontrato_humaportedetalle_and_more'),
        ('turno', '0008_tursoporte'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurSoporteDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas', models.DecimalField(db_default=0, decimal_places=3, default=0, max_digits=10)),
                ('horas_descansos', models.DecimalField(db_default=0, decimal_places=3, default=0, max_digits=10)),
                ('horas_diurnas', models.DecimalField(db_default=0, decimal_places=3, default=0, max_digits=10)),
                ('horas_nocturnas', models.DecimalField(db_default=0, decimal_places=3, default=0, max_digits=10)),
                ('horas_festivas_diurnas', models.DecimalField(db_default=0, decimal_places=3, default=0, max_digits=10)),
                ('horas_festivas_nocturnas', models.DecimalField(db_default=0, decimal_places=3, default=0, max_digits=10)),
                ('horas_extras_diurnas', models.DecimalField(db_default=0, decimal_places=3, default=0, max_digits=10)),
                ('horas_extras_nocturnas', models.DecimalField(db_default=0, decimal_places=3, default=0, max_digits=10)),
                ('horas_extras_festivas_diurnas', models.DecimalField(db_default=0, decimal_places=3, default=0, max_digits=10)),
                ('horas_extras_festivas_nocturnas', models.DecimalField(db_default=0, decimal_places=3, default=0, max_digits=10)),
                ('horas_recargos_nocturnos', models.DecimalField(db_default=0, decimal_places=3, default=0, max_digits=10)),
                ('horas_recargos_festivos_diurnos', models.DecimalField(db_default=0, decimal_places=3, default=0, max_digits=10)),
                ('horas_recargos_festivos_nocturnos', models.DecimalField(db_default=0, decimal_places=3, default=0, max_digits=10)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='soportes_detalles_contrato_rel', to='humano.humcontrato')),
                ('soporte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='soportes_detalles_soporte_rel', to='turno.tursoporte')),
            ],
            options={
                'verbose_name': 'Soporte detalle',
                'verbose_name_plural': 'Soportes detalles',
                'db_table': 'tur_soporte_detalle',
                'ordering': ['-id'],
            },
        ),
    ]
