# Generated by Django 6.0.4 on 2026-06-23 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turno', '0009_tursoportedetalle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tursecuencia',
            name='codigo',
        ),
    ]
