# Generated by Django 6.0.4 on 2026-06-23 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0008_humaporte_humaportecontrato_humaportedetalle_and_more'),
        ('turno', '0010_remove_tursecuencia_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='turturno',
            name='novedad_tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='turnos_novedad_tipo_rel', to='humano.humnovedadtipo'),
        ),
    ]
