# Generated by Django 6.0.4 on 2026-06-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turno', '0011_turturno_novedad_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='turturno',
            name='descanso',
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
