# Generated by Django 6.0.4 on 2026-07-04 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humano', '0009_humcontrato_habilitado_turno'),
        ('turno', '0013_programacion_turno_detalle_obligatorios'),
    ]

    operations = [
        migrations.AddField(
            model_name='turprototipo',
            name='contrato',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='prototipos_contrato_rel', to='humano.humcontrato'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='turprototipo',
            name='secuencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='prototipos_secuencia_rel', to='turno.tursecuencia'),
            preserve_default=False,
        ),
    ]
