# Generated by Django 6.0.4 on 2026-07-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turno', '0014_turprototipo_contrato_alter_turprototipo_secuencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='turprototipo',
            name='posicion',
            field=models.IntegerField(db_default=1, default=1),
        ),
    ]
