# Generated by Django 6.0.4 on 2026-07-11 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0057_genpais_estado_inactivo_alter_genpais_id'),
        ('humano', '0009_humcontrato_habilitado_turno'),
        ('turno', '0015_turprototipo_posicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='turprogramacionsimulacion',
            name='contrato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programaciones_simulacion_contrato_rel', to='humano.humcontrato'),
        ),
        migrations.AddField(
            model_name='turprogramacionsimulacion',
            name='documento_detalle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programaciones_simulacion_documento_detalle_rel', to='general.gendocumentodetalle'),
        ),
        migrations.AddField(
            model_name='turprogramacionsimulacion',
            name='posicion',
            field=models.IntegerField(db_default=1, default=1),
        ),
    ]
