# Generated by Django 6.0.4 on 2026-07-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0057_genpais_estado_inactivo_alter_genpais_id'),
        ('humano', '0009_humcontrato_habilitado_turno'),
        ('turno', '0016_turprogramacionsimulacion_contrato_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='turprototipo',
            constraint=models.UniqueConstraint(fields=('contrato', 'documento_detalle'), name='tur_prototipo_contrato_documento_detalle_unico'),
        ),
    ]
