# Generated by Django 6.0.4 on 2026-05-05 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0004_alter_ctncliente_schema_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CtnMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('factura', 'Factura'), ('recibo', 'Recibo')], max_length=10)),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('concepto', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('periodo', models.DateField(help_text='Primer día del mes que cubre el movimiento')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('vencida', 'Vencida'), ('anulada', 'Anulada')], default='pendiente', max_length=10)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('movimiento_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recibos', to='contenedor.ctnmovimiento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'db_table': 'ctn_movimiento',
            },
        ),
        migrations.CreateModel(
            name='CtnEventoPasarela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('evento', models.CharField(max_length=50, null=True)),
                ('entorno', models.CharField(max_length=10, null=True)),
                ('transaccion', models.CharField(max_length=50, null=True)),
                ('metodo_pago', models.CharField(max_length=50, null=True)),
                ('referencia', models.CharField(max_length=500, null=True)),
                ('correo', models.CharField(max_length=250, null=True)),
                ('estado', models.CharField(max_length=50, null=True)),
                ('fecha_transaccion', models.DateTimeField(null=True)),
                ('estado_aplicado', models.BooleanField(default=False)),
                ('vr_original', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('datos', models.JSONField(blank=True, null=True)),
                ('movimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_pasarela', to='contenedor.ctnmovimiento')),
            ],
            options={
                'verbose_name': 'Evento pasarela',
                'verbose_name_plural': 'Eventos pasarela',
                'db_table': 'ctn_evento_pasarela',
            },
        ),
    ]
