# Generated by Django 6.0.4 on 2026-05-08 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0005_billing_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='CtnEstado',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'ctn_estado',
            },
        ),
        migrations.CreateModel(
            name='CtnPais',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('codigo', models.CharField(max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'db_table': 'ctn_pais',
            },
        ),
        migrations.CreateModel(
            name='CtnCiudad',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('codigo_postal', models.CharField(max_length=10, null=True)),
                ('porcentaje_impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciudades', to='contenedor.ctnestado')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'db_table': 'ctn_ciudad',
            },
        ),
        migrations.AddField(
            model_name='ctnestado',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='contenedor.ctnpais'),
        ),
    ]
