# Generated by Django 6.0.4 on 2026-05-08 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0006_ctnestado_ctnpais_ctnciudad_ctnestado_pais'),
    ]

    operations = [
        migrations.CreateModel(
            name='CtnIdentificacion',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('orden', models.BigIntegerField(default=0)),
                ('codigo', models.CharField(max_length=10, null=True)),
                ('pais', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identificaciones', to='contenedor.ctnpais')),
            ],
            options={
                'db_table': 'ctn_identificacion',
            },
        ),
    ]
