# Generated by Django 6.0.4 on 2026-05-08 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0007_ctnidentificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CtnPlan',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('limite_usuarios', models.IntegerField(default=0)),
                ('usuarios_base', models.IntegerField(default=0)),
                ('limite_ingresos', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('precio_usuario_adicional', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('limite_electronicos', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('plan_tipo_id', models.CharField(max_length=1, null=True)),
                ('orden', models.IntegerField(default=0)),
                ('compra', models.BooleanField(default=False)),
                ('tesoreria', models.BooleanField(default=False)),
                ('venta', models.BooleanField(default=False)),
                ('cartera', models.BooleanField(default=False)),
                ('inventario', models.BooleanField(default=False)),
                ('humano', models.BooleanField(default=False)),
                ('contabilidad', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ctn_plan',
                'ordering': ['-id'],
            },
        ),
    ]
