# Generated by Django 6.0.4 on 2026-05-08 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0008_ctnplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CtnDatosFacturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_identificacion', models.CharField(max_length=20, null=True)),
                ('digito_verificacion', models.CharField(max_length=1, null=True)),
                ('nombre_corto', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=50, null=True)),
                ('telefono', models.CharField(max_length=50, null=True)),
                ('correo', models.EmailField(max_length=255)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datos_facturacion', to='contenedor.ctnciudad')),
                ('identificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datos_facturacion', to='contenedor.ctnidentificacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datos_facturacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ctn_datos_facturacion',
            },
        ),
    ]
