# Generated by Django 6.0.4 on 2026-05-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0009_ctndatosfacturacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctncliente',
            name='correo',
            field=models.EmailField(default='', max_length=255, verbose_name='Correo'),
        ),
        migrations.AddField(
            model_name='ctncliente',
            name='telefono',
            field=models.CharField(default='', max_length=20, verbose_name='Teléfono'),
        ),
    ]
