# Generated by Django 6.0.4 on 2026-05-09 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0010_agregar_telefono_correo_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctncliente',
            name='correo',
            field=models.EmailField(max_length=255, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='ctncliente',
            name='telefono',
            field=models.CharField(max_length=20, verbose_name='Teléfono'),
        ),
        migrations.CreateModel(
            name='CtnSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suscripciones', to='contenedor.ctncliente')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
                'db_table': 'ctn_suscripcion',
            },
        ),
    ]
