# Generated by Django 6.0.4 on 2026-05-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0011_suscripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CtnSuscripcionTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
            options={
                'verbose_name': 'Tipo de suscripción',
                'verbose_name_plural': 'Tipos de suscripción',
                'db_table': 'ctn_suscripcion_tipo',
            },
        ),
    ]
