# Generated by Django 6.0.4 on 2026-05-09 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0012_suscripcion_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctnsuscripcion',
            name='suscripcion_tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suscripciones', to='contenedor.ctnsuscripciontipo'),
        ),
    ]
