# Generated by Django 6.0.4 on 2026-05-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0013_suscripcion_add_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctnsuscripciontipo',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
