# Generated by Django 6.0.4 on 2026-05-09 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0014_suscripcion_tipo_id_manual'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CtnPlan',
        ),
    ]
