# Generated by Django 6.0.4 on 2026-05-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0015_eliminar_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctnsuscripciontipo',
            name='suscripcion_clase_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
