# Generated by Django 6.0.4 on 2026-05-09 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0016_suscripcion_tipo_add_clase_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctnsuscripcion',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to='contenedor.ctncliente'),
        ),
    ]
