# Generated by Django 6.0.4 on 2026-05-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0018_suscripcion_add_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctnsuscripciontipo',
            name='suscripcion_categoria_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
