# Generated by Django 6.0.4 on 2026-05-11 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0019_suscripcion_tipo_add_categoria_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctncliente',
            name='suscripcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenedor.ctnsuscripcion'),
        ),
    ]
