# Generated by Django 6.0.4 on 2026-05-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0020_cliente_add_suscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctnsuscripcion',
            name='frecuencia',
            field=models.CharField(blank=True, choices=[('M', 'Mensual'), ('A', 'Anual')], max_length=1, null=True),
        ),
    ]
