# Generated by Django 6.0.4 on 2026-05-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0021_suscripcion_add_frecuencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctnsuscripcion',
            name='frecuencia',
            field=models.CharField(choices=[('M', 'Mensual'), ('A', 'Anual'), ('P', 'Prueba')], default='M', max_length=1),
        ),
    ]
