# Generated by Django 6.0.4 on 2026-05-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0023_rename_evento_pasarela_a_evento_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ctnmovimiento',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='ctnmovimiento',
            name='movimiento_origen',
        ),
        migrations.RemoveField(
            model_name='ctnmovimiento',
            name='periodo',
        ),
        migrations.AlterField(
            model_name='ctnmovimiento',
            name='numero',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='ctnmovimiento',
            name='tipo',
            field=models.CharField(max_length=20),
        ),
    ]
