# Generated by Django 6.0.4 on 2026-05-13 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0030_movimiento_add_contacto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CtnInvitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254)),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('A', 'Aceptada'), ('R', 'Rechazada')], default='P', max_length=1)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('fecha_expira', models.DateTimeField()),
                ('token', models.CharField(max_length=500, unique=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones', to='contenedor.ctncliente')),
                ('invitado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invitaciones_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invitación',
                'verbose_name_plural': 'Invitaciones',
                'db_table': 'ctn_invitacion',
                'unique_together': {('cliente', 'correo')},
            },
        ),
    ]
