# Generated by Django 6.0.4 on 2026-05-13 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0031_agregar_invitacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ctninvitacion',
            name='fecha_expira',
        ),
        migrations.RemoveField(
            model_name='ctninvitacion',
            name='token',
        ),
    ]
