# Generated by Django 6.0.4 on 2026-05-14 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0034_invitacion_refactor_campos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='ctninvitacion',
            old_name='fecha_envio',
            new_name='fecha',
        ),
        migrations.AlterField(
            model_name='ctninvitacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones_enviadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
