# Generated by Django 6.0.4 on 2026-05-14 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0035_invitacion_rename_fecha_envio_a_fecha'),
        ('seguridad', '0010_rol_add_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctninvitacion',
            name='rol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitaciones', to='seguridad.segrol'),
        ),
    ]
