# Generated by Django 6.0.4 on 2026-05-17 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0036_invitacion_add_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctnsuscripcion',
            name='referencia_pago',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
