# Generated by Django 6.0.4 on 2026-05-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0037_ctnsuscripcion_referencia_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctnciudad',
            name='porcentaje_impuesto',
            field=models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='ctncliente',
            name='activo',
            field=models.BooleanField(db_default=True, default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='ctneventopago',
            name='estado_aplicado',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='ctneventopago',
            name='vr_original',
            field=models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='ctnidentificacion',
            name='orden',
            field=models.BigIntegerField(db_default=0, default=0),
        ),
        migrations.AlterField(
            model_name='ctninvitacion',
            name='estado',
            field=models.CharField(choices=[('P', 'Pendiente'), ('A', 'Aceptada'), ('R', 'Rechazada')], db_default='P', default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='ctnsuscripcion',
            name='frecuencia',
            field=models.CharField(choices=[('M', 'Mensual'), ('A', 'Anual'), ('P', 'Prueba')], db_default='M', default='M', max_length=1),
        ),
    ]
