# Generated by Django 6.0.4 on 2026-05-27 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0038_alter_ctnciudad_porcentaje_impuesto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctnmovimiento',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='contenedor.ctncliente'),
        ),
    ]
