# Generated by Django 6.0.4 on 2026-05-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0039_ctnmovimiento_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctnsuscripcion',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
    ]
