# Generated by Django 6.0.4 on 2026-05-27 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0040_ctnsuscripcion_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctnmovimiento',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='contenedor.ctncliente'),
        ),
    ]
