# Generated by Django 6.0.4 on 2026-05-27 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0041_alter_ctnmovimiento_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctnsuscripcion',
            name='precio',
            field=models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=14),
        ),
    ]
