# Generated by Django 6.0.4 on 2026-06-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0042_alter_ctnsuscripcion_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctnpais',
            name='estado_inactivo',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='ctnpais',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
