# Generated by Django 5.2.13 on 2026-08-06 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenedor', '0043_ctnpais_estado_inactivo_alter_ctnpais_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CtnInvitacionGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(db_column='grupo_id', on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('invitacion', models.ForeignKey(db_column='invitacion_id', on_delete=django.db.models.deletion.CASCADE, to='contenedor.ctninvitacion')),
            ],
            options={
                'db_table': 'ctn_invitacion_grupo',
                'unique_together': {('invitacion', 'grupo')},
            },
        ),
        migrations.AddField(
            model_name='ctninvitacion',
            name='grupos',
            field=models.ManyToManyField(blank=True, related_name='invitaciones', through='contenedor.CtnInvitacionGrupo', to='auth.group'),
        ),
    ]
