# Generated by Django 5.2.13 on 2026-08-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0044_ctninvitaciongrupo_ctninvitacion_grupos'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctninvitacion',
            name='acceso_cartera',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='ctninvitacion',
            name='acceso_compra',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='ctninvitacion',
            name='acceso_contabilidad',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='ctninvitacion',
            name='acceso_humano',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='ctninvitacion',
            name='acceso_inventario',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='ctninvitacion',
            name='acceso_tesoreria',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='ctninvitacion',
            name='acceso_turno',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='ctninvitacion',
            name='acceso_venta',
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
