# Generated by Django 5.2.13 on 2026-08-07 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0045_ctninvitacion_acceso_cartera_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ctninvitacion',
            name='rol',
        ),
    ]
