# Generated by Django 5.2.13 on 2026-09-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0048_rename_telefono_celular_ctncontacto'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ctneventopago',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'APPROVED')), fields=('transaccion',), name='ctn_evento_pago_transaccion_aprobada_unica'),
        ),
    ]
