# Generated by Django 5.2.13 on 2026-09-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0049_evento_pago_transaccion_aprobada_unica'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctncliente',
            name='estado',
            field=models.CharField(choices=[('creando', 'Creando'), ('listo', 'Listo'), ('error', 'Error')], db_default='listo', default='listo', max_length=10, verbose_name='Estado'),
        ),
    ]
