from .programacion import TurProgramacion
from .programacion_simulacion import TurProgramacionSimulacion
from .programador import TurProgramador
from .prototipo import TurPrototipo
from .puesto import TurPuesto
from .secuencia import TurSecuencia
from .soporte import TurSoporte
from .soporte_detalle import TurSoporteDetalle
from .turno import TurTurno
